"""Spheres of society (item 15): the design tables the engine reads, copied from chroma-ideas/spheres-data/ by
tools/sphere_tables.py. Do not edit by hand: change the data and copy again (--check compares).
Order of spheres: rule gather arts faith care learn prod comm prot; colours W U B R G."""
SPHERES = ['rule', 'gather', 'arts', 'faith', 'care', 'learn', 'prod', 'comm', 'prot']
COLORS = ['W', 'U', 'B', 'R', 'G']
EPOCHS = ['bands', 'villages', 'cities', 'realms', 'sail', 'machine', 'modern', 'magic']
DRIVERS = ['insecurity', 'plenty', 'war', 'crowding', 'inequality', 'schooling', 'exposure', 'change']
FACE_NEEDS = ['safety', 'belonging', 'meaning']
M0 = {'bands': [[0.25, 0.159, 0.201, 0.18, 0.21],
           [0.18, 0.169, 0.201, 0.22, 0.23],
           [0.17, 0.229, 0.201, 0.25, 0.15],
           [0.19, 0.229, 0.251, 0.16, 0.17],
           [0.19, 0.268, 0.172, 0.17, 0.2],
           [0.18, 0.199, 0.191, 0.21, 0.22],
           [0.18, 0.179, 0.181, 0.25, 0.21],
           [0.22, 0.169, 0.201, 0.15, 0.26],
           [0.24, 0.199, 0.201, 0.21, 0.15]],
 'villages': [[0.2, 0.18, 0.24, 0.16, 0.22],
              [0.24, 0.15, 0.18, 0.23, 0.2],
              [0.18, 0.22, 0.18, 0.26, 0.16],
              [0.21, 0.2, 0.19, 0.17, 0.23],
              [0.19, 0.27, 0.16, 0.18, 0.2],
              [0.17, 0.24, 0.19, 0.19, 0.21],
              [0.18, 0.18, 0.22, 0.19, 0.23],
              [0.25, 0.17, 0.22, 0.16, 0.2],
              [0.18, 0.19, 0.22, 0.26, 0.15]],
 'cities': [[0.238, 0.192, 0.219, 0.17, 0.181],
            [0.189, 0.161, 0.209, 0.25, 0.191],
            [0.209, 0.231, 0.189, 0.19, 0.181],
            [0.209, 0.181, 0.229, 0.18, 0.201],
            [0.189, 0.221, 0.159, 0.19, 0.241],
            [0.189, 0.241, 0.209, 0.18, 0.181],
            [0.189, 0.211, 0.159, 0.18, 0.261],
            [0.179, 0.181, 0.248, 0.22, 0.172],
            [0.209, 0.181, 0.179, 0.24, 0.191]],
 'realms': [[0.179, 0.221, 0.25, 0.17, 0.18],
            [0.169, 0.161, 0.19, 0.27, 0.21],
            [0.179, 0.231, 0.18, 0.25, 0.16],
            [0.199, 0.191, 0.19, 0.17, 0.25],
            [0.199, 0.221, 0.16, 0.17, 0.25],
            [0.209, 0.251, 0.18, 0.18, 0.18],
            [0.239, 0.161, 0.22, 0.15, 0.23],
            [0.179, 0.211, 0.24, 0.2, 0.17],
            [0.248, 0.152, 0.19, 0.24, 0.17]],
 'sail': [[0.21, 0.2, 0.22, 0.17, 0.2],
          [0.2, 0.23, 0.17, 0.22, 0.18],
          [0.16, 0.2, 0.21, 0.24, 0.19],
          [0.22, 0.18, 0.15, 0.25, 0.2],
          [0.18, 0.18, 0.2, 0.18, 0.26],
          [0.25, 0.2, 0.17, 0.19, 0.19],
          [0.17, 0.21, 0.23, 0.17, 0.22],
          [0.2, 0.23, 0.21, 0.18, 0.18],
          [0.21, 0.17, 0.24, 0.2, 0.18]],
 'machine': [[0.219, 0.201, 0.19, 0.209, 0.181],
             [0.198, 0.141, 0.17, 0.209, 0.282],
             [0.159, 0.201, 0.24, 0.229, 0.171],
             [0.199, 0.172, 0.15, 0.248, 0.231],
             [0.189, 0.251, 0.18, 0.149, 0.231],
             [0.229, 0.221, 0.21, 0.169, 0.171],
             [0.209, 0.181, 0.2, 0.229, 0.181],
             [0.189, 0.201, 0.26, 0.169, 0.181],
             [0.209, 0.231, 0.2, 0.189, 0.171]],
 'modern': [[0.231, 0.197, 0.19, 0.191, 0.191],
            [0.181, 0.167, 0.19, 0.221, 0.241],
            [0.161, 0.187, 0.24, 0.231, 0.181],
            [0.201, 0.187, 0.17, 0.191, 0.251],
            [0.202, 0.236, 0.16, 0.181, 0.221],
            [0.201, 0.225, 0.21, 0.182, 0.182],
            [0.181, 0.197, 0.21, 0.231, 0.181],
            [0.201, 0.207, 0.24, 0.181, 0.171],
            [0.241, 0.197, 0.19, 0.191, 0.181]],
 'magic': [[0.21, 0.24, 0.2, 0.16, 0.19],
           [0.18, 0.17, 0.2, 0.22, 0.23],
           [0.16, 0.24, 0.2, 0.22, 0.18],
           [0.18, 0.18, 0.21, 0.19, 0.24],
           [0.25, 0.18, 0.17, 0.16, 0.24],
           [0.19, 0.22, 0.23, 0.17, 0.19],
           [0.2, 0.21, 0.18, 0.22, 0.19],
           [0.19, 0.19, 0.22, 0.23, 0.17],
           [0.24, 0.17, 0.19, 0.23, 0.17]]}
J = {'bands': [[0, 1, 1, 1, 0, 0, 0, 0.5, 0.5],
           [1, 0, 1, 1, 0.5, 0.5, 0.5, 0.5, 0.5],
           [1, 1, 0, 1, 0.5, 0.5, 0, 0, 0],
           [1, 1, 1, 0, 1, 0.5, 0.5, 0, 0],
           [0, 0.5, 0.5, 1, 0, 0.5, 0.5, 0, 0],
           [0, 0.5, 0.5, 0.5, 0.5, 0, 1, 0, 0],
           [0, 0.5, 0, 0.5, 0.5, 1, 0, 1, 1],
           [0.5, 0.5, 0, 0, 0, 0, 1, 0, 1],
           [0.5, 0.5, 0, 0, 0, 0, 1, 1, 0]],
 'villages': [[0, 0.5, 0, 1, 0, 0, 0, 0.5, 1],
              [0.5, 0, 1, 1, 0, 0, 0, 0.5, 0],
              [0, 1, 0, 1, 0, 0.5, 0.5, 0, 0],
              [1, 1, 1, 0, 0.5, 0.5, 0.5, 0.5, 0],
              [0, 0, 0, 0.5, 0, 1, 1, 0, 0],
              [0, 0, 0.5, 0.5, 1, 0, 1, 0, 0],
              [0, 0, 0.5, 0.5, 1, 1, 0, 0.5, 0.5],
              [0.5, 0.5, 0, 0.5, 0, 0, 0.5, 0, 0],
              [1, 0, 0, 0, 0, 0, 0.5, 0, 0]],
 'cities': [[0, 0, 0.5, 0.5, 0, 0.5, 0.5, 0.5, 1],
            [0, 0, 0.5, 0.5, 0, 0, 0, 0.5, 0],
            [0.5, 0.5, 0, 1, 0, 0, 0, 0, 0],
            [0.5, 0.5, 1, 0, 0.5, 0.5, 0.5, 0.5, 0],
            [0, 0, 0, 0.5, 0, 0.5, 0, 0, 0],
            [0.5, 0, 0, 0.5, 0.5, 0, 0.5, 0.5, 0],
            [0.5, 0, 0, 0.5, 0, 0.5, 0, 0.5, 0],
            [0.5, 0.5, 0, 0.5, 0, 0.5, 0.5, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0, 0]],
 'realms': [[0, 0, 0.5, 0.5, 0, 0, 0.5, 0.5, 1],
            [0, 0, 0.5, 0.5, 0, 0, 0.5, 0.5, 0.5],
            [0.5, 0.5, 0, 0.5, 0, 0, 0.5, 0, 0],
            [0.5, 0.5, 0.5, 0, 0.5, 1, 0.5, 0, 0],
            [0, 0, 0, 0.5, 0, 0, 0.5, 0.5, 0],
            [0, 0, 0, 1, 0, 0, 0.5, 0, 0],
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0, 1, 0],
            [0.5, 0.5, 0, 0, 0.5, 0, 1, 0, 0.5],
            [1, 0.5, 0, 0, 0, 0, 0, 0.5, 0]],
 'sail': [[0, 0.5, 0, 0.5, 0, 0, 0, 0.5, 0.5],
          [0.5, 0, 0.5, 0, 0, 0.5, 0, 0.5, 0],
          [0, 0.5, 0, 0, 0, 0.5, 0, 0.5, 0],
          [0.5, 0, 0, 0, 0.5, 0.5, 0, 0, 0],
          [0, 0, 0, 0.5, 0, 0.5, 0.5, 0, 0],
          [0, 0.5, 0.5, 0.5, 0.5, 0, 0.5, 0.5, 0],
          [0, 0, 0, 0, 0.5, 0.5, 0, 0.5, 0.5],
          [0.5, 0.5, 0.5, 0, 0, 0.5, 0.5, 0, 0.5],
          [0.5, 0, 0, 0, 0, 0, 0.5, 0.5, 0]],
 'machine': [[0, 0.5, 0, 0, 0.5, 0.5, 0.5, 0, 0.5],
             [0.5, 0, 0.5, 0.5, 0, 0, 0.5, 0.5, 0],
             [0, 0.5, 0, 0, 0, 0, 0, 0.5, 0],
             [0, 0.5, 0, 0, 0.5, 0.5, 0, 0, 0],
             [0.5, 0, 0, 0.5, 0, 0.5, 0.5, 0, 0],
             [0.5, 0, 0, 0.5, 0.5, 0, 0.5, 0, 0],
             [0.5, 0.5, 0, 0, 0.5, 0.5, 0, 0.5, 0.5],
             [0, 0.5, 0.5, 0, 0, 0, 0.5, 0, 0],
             [0.5, 0, 0, 0, 0, 0, 0.5, 0, 0]],
 'modern': [[0, 0, 0, 0, 0.5, 0.5, 0, 0, 0.5],
            [0, 0, 0.5, 0.5, 0, 0, 0, 0.5, 0],
            [0, 0.5, 0, 0, 0, 0, 0, 0.5, 0],
            [0, 0.5, 0, 0, 0.5, 0, 0, 0, 0],
            [0.5, 0, 0, 0.5, 0, 0.5, 0, 0.5, 0],
            [0.5, 0, 0, 0, 0.5, 0, 0.5, 0, 0],
            [0, 0, 0, 0, 0, 0.5, 0, 0.5, 0],
            [0, 0.5, 0.5, 0, 0.5, 0, 0.5, 0, 0.5],
            [0.5, 0, 0, 0, 0, 0, 0, 0.5, 0]],
 'magic': [[0, 0, 0, 0.5, 0.5, 0.5, 0.5, 0.5, 1],
           [0, 0, 0.5, 0.5, 0, 0.5, 0.5, 0.5, 0.5],
           [0, 0.5, 0, 0.5, 0, 0, 0, 0.5, 0],
           [0.5, 0.5, 0.5, 0, 0.5, 0.5, 0.5, 0, 0.5],
           [0.5, 0, 0, 0.5, 0, 0.5, 0, 0, 0.5],
           [0.5, 0.5, 0, 0.5, 0.5, 0, 0.5, 0, 0.5],
           [0.5, 0.5, 0, 0.5, 0, 0.5, 0, 1, 0],
           [0.5, 0.5, 0.5, 0, 0, 0, 1, 0, 0.5],
           [1, 0.5, 0, 0.5, 0.5, 0.5, 0, 0.5, 0]]}
D = {'insecurity': [[1, 2, -1, -1, -1],
                [1, -1, 2, -2, 0],
                [1, -1, -1, 1, 0],
                [1, -1, -1, 2, -1],
                [0, -1, -2, 2, 1],
                [-2, 0, 1, 0, 1],
                [0, 0, -1, -1, 2],
                [-1, 2, 1, -1, -1],
                [-1, 0, 2, -2, 1]],
 'plenty': [[1, 0, 2, -2, -1],
            [-1, -2, 0, 1, 2],
            [-1, 0, 1, 0, 0],
            [-1, 1, 0, -2, 2],
            [1, 1, 0, -1, -1],
            [2, 1, -2, 0, -1],
            [-2, 0, 2, 1, -1],
            [-1, -1, 0, 2, 0],
            [2, -1, -2, 1, 0]],
 'war': [[0, 1, -1, 0, 0],
         [2, -2, -1, 0, 1],
         [0, -1, 1, -1, 1],
         [1, -1, 1, 1, -2],
         [-1, 1, -1, 2, -1],
         [-1, 0, -1, 1, 1],
         [-1, 2, 1, -1, -1],
         [1, -1, 0, -1, 1],
         [0, 2, -1, 0, -1]],
 'crowding': [[1, 1, 0, 0, -2],
              [-1, -1, 0, 0, 2],
              [-2, 0, 1, 2, -1],
              [-2, 0, 0, 1, 1],
              [2, 0, 0, -1, -1],
              [2, 0, 0, -1, -1],
              [-1, -1, 1, 0, 1],
              [-1, -1, -1, 1, 2],
              [1, 1, 1, -1, -2]],
 'inequality': [[0, -1, 2, 1, -2],
                [0, -1, 2, -1, 0],
                [-1, 1, 0, 0, 0],
                [1, -1, -1, 1, 0],
                [-1, -1, 1, 0, 1],
                [1, 1, -1, -1, 0],
                [2, 1, -1, -1, -1],
                [0, 0, -1, 0, 1],
                [-2, 1, 0, 1, 0]],
 'schooling': [[1, 0, -2, 2, -1],
               [0, 0, 0, 1, -1],
               [-1, -1, 0, 1, 1],
               [-1, 1, 2, -1, -1],
               [0, 1, -1, -1, 1],
               [2, -1, -1, -1, 1],
               [-1, 0, 1, -1, 1],
               [1, 1, -1, -2, 1],
               [1, 0, 0, 0, -1]],
 'exposure': [[1, 1, -1, 1, -2],
              [0, 1, 0, -1, 0],
              [-1, 0, 2, 0, -1],
              [-2, 1, 0, 0, 1],
              [-1, -1, 0, 1, 1],
              [1, -1, -1, 0, 1],
              [1, -2, 1, 0, 0],
              [2, 1, -1, -1, -1],
              [-1, -1, 0, 1, 1]],
 'change': [[-1, 1, 0, 1, -1],
            [-1, 0, 0, 2, -1],
            [-1, 1, 0, 0, 0],
            [-1, 0, 1, 0, 0],
            [1, 1, 0, -1, -1],
            [1, -1, 0, 0, 0],
            [1, 0, 0, -2, 1],
            [1, -2, 1, -1, 1],
            [0, 2, 0, -1, -1]]}
MEETS = [[[0.289, 0.121, 0.19], [0.258, 0.059, 0.283], [0.231, 0.117, 0.252], [0.181, 0.247, 0.172], [0.218, 0.269, 0.113]],
 [[0.174, 0.226, 0.2], [0.098, 0.209, 0.293], [0.116, 0.267, 0.217], [0.081, 0.412, 0.107], [0.148, 0.374, 0.078]],
 [[0.174, 0.146, 0.28], [0.113, 0.099, 0.388], [0.116, 0.142, 0.342], [0.081, 0.332, 0.187], [0.118, 0.339, 0.143]],
 [[0.174, 0.166, 0.26], [0.113, 0.119, 0.368], [0.146, 0.147, 0.307], [0.066, 0.337, 0.197], [0.118, 0.329, 0.153]],
 [[0.294, 0.166, 0.14], [0.278, 0.119, 0.203], [0.251, 0.177, 0.172], [0.201, 0.307, 0.092], [0.238, 0.299, 0.063]],
 [[0.229, 0.121, 0.25], [0.153, 0.059, 0.388], [0.171, 0.117, 0.312], [0.106, 0.277, 0.217], [0.188, 0.254, 0.158]],
 [[0.309, 0.141, 0.15], [0.233, 0.079, 0.288], [0.236, 0.122, 0.242], [0.201, 0.267, 0.132], [0.268, 0.274, 0.058]],
 [[0.289, 0.141, 0.17], [0.258, 0.079, 0.263], [0.231, 0.137, 0.232], [0.181, 0.267, 0.152], [0.218, 0.289, 0.093]],
 [[0.314, 0.126, 0.16], [0.298, 0.079, 0.223], [0.301, 0.122, 0.177], [0.251, 0.252, 0.097], [0.288, 0.274, 0.038]]]
FACE_NAMES = {'rule.W': 'A fair hearing',
 'rule.U': 'Reasoned law',
 'rule.B': 'Favour and following',
 'rule.R': 'Raised voices',
 'rule.G': 'Old custom',
 'gather.W': 'No one left out',
 'gather.U': 'Good talk',
 'gather.B': 'Useful company',
 'gather.R': 'High spirits',
 'gather.G': 'Familiar faces',
 'arts.W': 'Art that binds',
 'arts.U': 'True form',
 'arts.B': 'Making a name',
 'arts.R': 'Raw feeling',
 'arts.G': 'Living tradition',
 'faith.W': 'Mercy and duty',
 'faith.U': 'Seeking truth',
 'faith.B': 'Chosen path',
 'faith.R': 'Living fire',
 'faith.G': 'Ancestors and seasons',
 'care.W': 'Care for all',
 'care.U': 'Proven cure',
 'care.B': 'Chosen healer',
 'care.R': 'Rush to help',
 'care.G': 'Kin who carry',
 'learn.W': 'Every child taught',
 'learn.U': 'Pure inquiry',
 'learn.B': 'Getting ahead',
 'learn.R': 'Learn by doing',
 'learn.G': 'Handed-down knowing',
 'prod.W': 'Honest work',
 'prod.U': 'Better methods',
 'prod.B': 'Own account',
 'prod.R': 'Free hand',
 'prod.G': 'For those who come after',
 'comm.W': 'Fair measure',
 'comm.U': 'Careful reckoning',
 'comm.B': 'Shrewd bargain',
 'comm.R': 'Haggle and dare',
 'comm.G': 'Gift and return',
 'prot.W': 'Equal protection',
 'prot.U': 'Early warning',
 'prot.B': 'Skill at a price',
 'prot.R': 'Courage first',
 'prot.G': 'Defend our own'}
PARAMS = {'native_centre': {'source': 'epochs.json round2.M0[epoch][sphere]: five shares, W U B R G, summing to 1',
                   'modern': 'epochs.json round2.native_centre_fixed (the same as M0.modern)',
                   'epoch_turn': "M0 moves .01 a quarter toward the new epoch's table"},
 'kN': 4.0,
 'kS': 5.0,
 'need_mem': 0.02,
 'kQ': 0.3,
 'sec_mem': 0.01,
 'kO': 0.2,
 'y_mem': 0.01,
 'k_drivers': {'war': 0.3, 'crowding': 0.2, 'inequality': 0.15, 'schooling': 0.15, 'exposure': 0.2, 'change': 0.2},
 'drv_mem': {'war': 0.005, 'others': 0.01},
 'kK': 5.0,
 'sig_big': 0.4,
 'sig_local': 0.2,
 'rho': {'comm': 0.05,
         'gather': 0.05,
         'arts': 0.05,
         'prod': 0.04,
         'prot': 0.03,
         'care': 0.025,
         'learn': 0.025,
         'rule': 0.02,
         'faith': 0.02},
 'sL': 0.05,
 'mu': 0.7,
 'smooth_n': 20,
 'aH': 0.0015,
 'H_mem': 0.007,
 'aL': 0.01,
 'kOl': 1.0,
 'tenure_q': 24,
 'kPat': 0.05,
 'aA': 0.02,
 's_min': 0.02,
 'base_share': {'order': 'rule gather arts faith care learn prod comm prot',
                'bands': [0.04, 0.2, 0.08, 0.07, 0.04, 0.04, 0.45, 0.04, 0.04],
                'villages': [0.04, 0.13, 0.05, 0.08, 0.03, 0.03, 0.55, 0.05, 0.04],
                'cities': [0.05, 0.1, 0.04, 0.08, 0.03, 0.04, 0.48, 0.12, 0.06],
                'realms': [0.04, 0.1, 0.04, 0.09, 0.03, 0.03, 0.5, 0.11, 0.06],
                'sail': [0.04, 0.11, 0.05, 0.07, 0.03, 0.04, 0.45, 0.15, 0.06],
                'machine': [0.04, 0.09, 0.04, 0.05, 0.03, 0.08, 0.5, 0.13, 0.04],
                'modern': [0.05, 0.09, 0.12, 0.02, 0.12, 0.15, 0.2, 0.22, 0.03],
                'magic': [0.04, 0.1, 0.05, 0.1, 0.03, 0.05, 0.46, 0.11, 0.06]},
 'eps': {'prod': 0.5,
         'faith': 0.5,
         'prot': 0.8,
         'gather': 1.0,
         'comm': 1.1,
         'rule': 1.1,
         'learn': 1.2,
         'care': 1.3,
         'arts': 1.3},
 'beta': {'learn': 1.0, 'care': 1.0, 'prot': 0.5, 'rule': 0.5},
 'phi': {'learn<15': 1.5, 'gather15-29': 0.8, 'arts15-29': 0.8, 'prot15-29': 0.8, 'care65+': 2.0, 'faith65+': 0.8},
 'alpha_prod': 0.6,
 'zeta': {'arts': 0.3, 'gather': -0.2},
 'delta': {'bands': 0.1,
           'villages': 0.25,
           'cities': 0.5,
           'realms': 0.55,
           'sail': 0.65,
           'machine': 0.8,
           'modern': 0.9,
           'magic': 0.5},
 'kZ': 0.03,
 'war_jump': {'prot': 3.0, 'rule': 1.3, 'ratchet_kept': 0.33},
 'plague_jump': {'care': 2.0, 'gather': 0.5},
 'pair_share': 0.25,
 'pair_quarters': 8,
 'pair_person': 0.26,
 'pair_rise': 0.1,
 'pair_decay': 0.05,
 'pair_calm': 0.3,
 'omega': {'child': [0.65, 0.25, 0.05, 0.05],
           'youth': [0.4, 0.25, 0.3, 0.05],
           'adult': [0.5, 0.28, 0.17, 0.05],
           'old': [0.55, 0.25, 0.12, 0.08],
           'order': 'close, spheres, times, belief and abroad'},
 'depth': {'work': 0.15,
           'learn': 0.2,
           'haunt': 0.3,
           'faith': 0.35,
           'care given': 0.25,
           'service': 0.35,
           'civic': 0.25,
           'market': 0.1},
 'rung_w': 0.25,
 'times_age': {'10': 0.3, '15': 1.0, '25': 1.0, '40': 0.5, '70': 0.4},
 'g': 0.004,
 'v_calm': 0.02,
 'S_max': 3.0,
 'push_unmet': 0.3,
 'kap': {'voice': 0.03, 'subvert': 0.03},
 'rung_mult': [0.25, 0.5, 1.0, 1.5, 2.0],
 'REACH': [[3, 1, 0, 0], [3, 2, 1, 0], [3, 2, 2, 1], [3, 2, 3, 2]]}
SUBSECTORS = {'rule': ['counsel', 'office', 'judgment', 'law', 'sanction', 'voice'],
 'gather': ['house', 'hall', 'great', 'games', 'circle', 'night', 'talk'],
 'arts': ['song', 'stage', 'screen', 'tale', 'page', 'craft', 'rite'],
 'faith': ['congregation', 'rites', 'calendar', 'orders', 'works', 'seeking', 'shrines'],
 'care': ['hearth', 'birth', 'healers', 'physic', 'houses', 'rescue', 'public'],
 'learn': ['rearing', 'schooling', 'apprentice', 'higher', 'keeping', 'finding'],
 'prod': ['wild', 'land', 'ground', 'craft', 'works', 'founding'],
 'comm': ['gift', 'market', 'shop', 'far', 'credit', 'office', 'hire'],
 'prot': ['watch', 'host', 'hire', 'watchers', 'walls', 'rescue', 'holding']}
PLACE_BY_EPOCH = {'rule.counsel': {'bands': 'the council fire',
                  'villages': 'the meeting tree',
                  'cities': 'the assembly square',
                  'realms': 'the town council chamber',
                  'sail': 'the house of the estates',
                  'machine': 'the town hall',
                  'modern': 'the council chamber',
                  'magic': 'the Assembly floor'},
 'rule.office': {'bands': "the speaker's round of hearths",
                 'villages': "the chief's granary",
                 'cities': "the palace scribes' room",
                 'realms': "the steward's counting room",
                 'sail': "the crown's counting office",
                 'machine': 'the ministry office',
                 'modern': 'the agency office',
                 'magic': 'the Office of the Gift'},
 'rule.judgment': {'bands': 'the hearing at the fire',
                   'villages': 'the shrine of oaths',
                   'cities': 'the judges at the gate',
                   'realms': 'the manor court',
                   'sail': 'the assize court',
                   'machine': "the magistrates' court",
                   'modern': 'the courthouse',
                   'magic': "the Orders' court"},
 'rule.law': {'bands': 'the tellings at the fire',
              'villages': 'the tellings at the shrine',
              'cities': "the temple's law code",
              'realms': "the town's charter chest",
              'sail': 'the printed statute book',
              'machine': 'the law library',
              'modern': 'the law archive',
              'magic': 'the charter of workings'},
 'rule.sanction': {'bands': 'exile from the band',
                   'villages': 'the blood-price in cattle',
                   'cities': "the debtors' prison",
                   'realms': 'the stocks and the gaol',
                   'sail': 'the house of correction',
                   'machine': 'the town gaol',
                   'modern': 'the prison',
                   'magic': 'the warded cells'},
 'rule.voice': {'bands': 'the show of hands',
                'villages': "the lineages' choosing",
                'cities': 'the vote in the square',
                'realms': 'the guild election',
                'sail': 'the hustings',
                'machine': 'the polling station',
                'modern': 'the polling place',
                'magic': "the Assembly's lot-urns"},
 'gather.house': {'bands': 'the shared meat fire',
                  'villages': 'the brewing household',
                  'cities': 'the drinking house',
                  'realms': 'the alehouse and the inn',
                  'sail': 'the tavern and coffee house',
                  'machine': 'the corner tavern',
                  'modern': 'the bar and the café',
                  'magic': 'the crossroads inn'},
 'gather.hall': {'bands': 'the great longhouse',
                 'villages': 'the feast house',
                 'cities': "the burial club's room",
                 'realms': 'the guildhall',
                 'sail': 'the lodge room',
                 'machine': "the workers' club",
                 'modern': 'the community centre',
                 'magic': "the guild's feast hall"},
 'gather.great': {'bands': 'the summer gathering ground',
                  'villages': 'the green by the well',
                  'cities': 'the square at the gate',
                  'realms': 'the fairground and common',
                  'sail': 'the common and pleasure garden',
                  'machine': 'the public park',
                  'modern': 'the park and convention hall',
                  'magic': 'the market square'},
 'gather.games': {'bands': 'the wrestling ground',
                  'villages': 'the games at the shrine',
                  'cities': 'the racecourse',
                  'realms': 'the tournament field',
                  'sail': 'the river race and bowling green',
                  'machine': 'the match ground',
                  'modern': 'the sports ground',
                  'magic': 'the duelling yard'},
 'gather.circle': {'bands': 'the telling at the fire',
                   'villages': 'the winter fireside',
                   'cities': "the poets' drinking party",
                   'realms': "the inn's back table",
                   'sail': 'the salon and reading room',
                   'machine': 'the debating club',
                   'modern': 'the book group',
                   'magic': "the academy's salon"},
 'gather.night': {'bands': "the young people's own fire",
                  'villages': 'the harvest dance ground',
                  'cities': 'the festival dancing',
                  'realms': 'the alehouse on fair nights',
                  'sail': 'the pleasure garden',
                  'machine': 'the dance hall',
                  'modern': 'the night club',
                  'magic': "the outer wards' night tavern"},
 'gather.talk': {'bands': 'the talk at the fire',
                 'villages': 'the well-side',
                 'cities': 'the crier at the gate',
                 'realms': 'the crier and the inn',
                 'sail': 'the broadsheet read aloud',
                 'machine': 'the daily paper',
                 'modern': 'the news feed',
                 'magic': 'the crier and broadsheet'},
 'arts.song': {'bands': 'the dance ground',
               'villages': 'the threshing floor',
               'cities': 'the temple court',
               'realms': "the lord's great hall",
               'sail': 'the public concert room',
               'machine': 'the music hall and bandstand',
               'modern': 'the concert hall',
               'magic': "the bards' tavern"},
 'arts.stage': {'bands': "the masked dancers' ground",
                'villages': 'the mask dance at the shrine',
                'cities': 'the festival theatre',
                'realms': 'the pageant wagon and inn yard',
                'sail': 'the public playhouse',
                'machine': 'the theatre and opera house',
                'modern': 'the theatre',
                'magic': 'the illusion theatre'},
 'arts.screen': {'bands': 'shadows on the firelit rock',
                 'villages': 'the shadow show by lamplight',
                 'cities': 'the shadow-play booth',
                 'realms': 'the puppet booth at the fair',
                 'sail': 'the magic-lantern show',
                 'machine': 'the picture house',
                 'modern': 'the cinema and the home screen',
                 'magic': 'the light-play in the square'},
 'arts.tale': {'bands': 'the evening fire',
               'villages': 'the hearth in winter',
               'cities': "the market's storytelling corner",
               'realms': "the inn's fireside",
               'sail': 'the ballad stall and fireside',
               'machine': 'the kitchen fire on rest days',
               'modern': 'the fireside and the phone',
               'magic': "the tellers' corner of the night market"},
 'arts.page': {'bands': 'the telling learned by heart',
               'villages': "the praise singer's remembered line",
               'cities': "the scribes' house",
               'realms': "the copyists' room",
               'sail': 'the printshop and bookstall',
               'machine': 'the lending library',
               'modern': 'the bookshop',
               'magic': "the Crown's licensed press"},
 'arts.craft': {'bands': 'the painted cave',
                'villages': "the potter's yard",
                'cities': "the sculptors' workshop",
                'realms': "the master carver's workshop",
                'sail': "the engraver's shop",
                'machine': 'the exhibition hall',
                'modern': 'the gallery',
                'magic': "the mask-makers' row"},
 'arts.rite': {'bands': 'the summer gathering',
               'villages': 'the seed and harvest rites',
               'cities': 'the new year festival',
               'realms': 'the feast-day procession',
               'sail': 'the anniversary pageant',
               'machine': 'the memorial parade',
               'modern': 'the festival ground',
               'magic': "the realm's day of remembrance"},
 'faith.congregation': {'bands': 'the fire circle',
                        'villages': 'the village shrine',
                        'cities': 'the temple courtyard',
                        'realms': "the village faith's house",
                        'sail': 'the meeting house',
                        'machine': "the faith's hall",
                        'modern': 'the house of worship',
                        'magic': "the Temple's hall of rites"},
 'faith.rites': {'bands': "the ancestors' places",
                 'villages': 'the burial ground',
                 'cities': 'the tombs outside the walls',
                 'realms': "the faith's house and graveyard",
                 'sail': 'the meeting house burial ground',
                 'machine': 'the town cemetery',
                 'modern': 'the funeral home',
                 'magic': "the Veil's barrows"},
 'faith.calendar': {'bands': 'the midwinter dance ground',
                    'villages': 'the threshing floor at harvest',
                    'cities': 'the processional way',
                    'realms': 'the feast-day fair',
                    'sail': 'the feast-day table',
                    'machine': "the mills' holiday week",
                    'modern': 'the holidays at home',
                    'magic': 'the festival field'},
 'faith.orders': {'bands': 'the lore lodge',
                  'villages': "the diviner's hut",
                  'cities': "the priests' quarter",
                  'realms': 'the vowed house',
                  'sail': "the preachers' college",
                  'machine': "the faith's training college",
                  'modern': 'the retreat community',
                  'magic': "the Order's house"},
 'faith.works': {'bands': 'the meat-sharing fire',
                 'villages': "the shrine's harvest store",
                 'cities': 'the temple storehouse',
                 'realms': 'the alms door',
                 'sail': 'the charity school',
                 'machine': "the faith's soup kitchen",
                 'modern': 'the food bank',
                 'magic': "the Temple's house of healing"},
 'faith.seeking': {'bands': "the vision walk's lonely place",
                   'villages': 'the hill above the fields',
                   'cities': "the oracle's seat",
                   'realms': "the hermit's hut",
                   'sail': "the family's own book",
                   'machine': "the freethinkers' reading room",
                   'modern': 'the retreat house',
                   'magic': "the mystery circle's room"},
 'faith.shrines': {'bands': 'the painted caves',
                   'villages': 'the sacred spring',
                   'cities': 'the hill shrine',
                   'realms': 'the pilgrim road',
                   'sail': 'the pilgrim ship',
                   'machine': 'the pilgrim train',
                   'modern': 'the old walking road',
                   'magic': "the healing spring's shrine"},
 'care.hearth': {'bands': "the band's hearths",
                 'villages': 'the sickroom of the house',
                 'cities': 'the family courtyard',
                 'realms': 'the sickbed by the hearth',
                 'sail': "the family's upstairs sickroom",
                 'machine': 'the back kitchen',
                 'modern': 'the kitchen table at home',
                 'magic': 'the sickroom at home'},
 'care.birth': {'bands': 'the birth shelter',
                'villages': "the mother's house",
                'cities': 'the temple birthing room',
                'realms': 'the lying-in chamber',
                'sail': 'the lying-in hospital',
                'machine': "the district midwife's round",
                'modern': 'the maternity unit',
                'magic': "the midwives' house"},
 'care.healers': {'bands': "the plant-wise one's trail",
                  'villages': "the herbalist's garden",
                  'cities': "the herb-sellers' stalls",
                  'realms': "the apothecary's shop",
                  'sail': "the apothecary's counter",
                  'machine': "the chemist's shop",
                  'modern': 'the pharmacy',
                  'magic': "the hedge healer's door"},
 'care.physic': {'bands': "the healer's hearth",
                 'villages': "the bonesetter's yard",
                 'cities': "the physician's house",
                 'realms': 'the school of physic',
                 'sail': "the physician's consulting room",
                 'machine': "the doctor's surgery",
                 'modern': "the doctor's rooms",
                 'magic': "the academy's halls of physic"},
 'care.houses': {'bands': "the longhouse's warm room",
                 'villages': 'the healing shrine',
                 'cities': "the temple's court of healing",
                 'realms': "the vowed house's infirmary",
                 'sail': "the subscribers' hospital",
                 'machine': 'the general hospital',
                 'modern': 'the hospital',
                 'magic': "the temple's house of healing"},
 'care.rescue': {'bands': "the hunters' carry home",
                 'villages': 'the flooded ford',
                 'cities': "the city's fire watch",
                 'realms': 'the field tent',
                 'sail': 'the rescue boat house',
                 'machine': 'the works first-aid room',
                 'modern': 'the ambulance and emergency room',
                 'magic': "the Ward's rescue post"},
 'care.public': {'bands': 'the clean spring upstream',
                 'villages': 'the village well',
                 'cities': 'the city wells and drains',
                 'realms': "the town's plague house",
                 'sail': 'the harbour quarantine station',
                 'machine': 'the board of health',
                 'modern': 'the health board',
                 'magic': "the Ward's plague watch"},
 'learn.rearing': {'bands': "the hearth and children's band",
                   'villages': 'the household and its fields',
                   'cities': 'the courtyard house',
                   'realms': 'the cottage hearth',
                   'sail': "the family's front room",
                   'machine': 'the home and the street',
                   'modern': 'the home and the nursery',
                   'magic': 'the home and hearth temple'},
 'learn.schooling': {'bands': 'the teaching at the fire',
                     'villages': 'the shrine yard lessons',
                     'cities': "the scribes' school",
                     'realms': 'the temple or guild school',
                     'sail': 'the grammar or charity school',
                     'machine': 'the board school',
                     'modern': 'the school',
                     'magic': "the quarter's school"},
 'learn.apprentice': {'bands': "the toolmaker's side",
                      'villages': 'the kin craft yard',
                      'cities': "the master's workshop",
                      'realms': "the guild master's workshop",
                      'sail': "the master's shop and yard",
                      'machine': "the works' training shop",
                      'modern': 'the training centre',
                      'magic': "the tower and artificers' bench"},
 'learn.higher': {'bands': 'the lore lodge',
                  'villages': "the shrine's deep-lore teaching",
                  'cities': 'the palace house of learning',
                  'realms': 'the university halls',
                  'sail': 'the university and learned society',
                  'machine': 'the research university',
                  'modern': 'the university',
                  'magic': 'the academy and the towers'},
 'learn.keeping': {'bands': "the tellers' memory",
                   'villages': "the shrine's tally store",
                   'cities': "the temple's tablet room",
                   'realms': "the vowed house's library",
                   'sail': 'the record house and library',
                   'machine': 'the public library',
                   'modern': 'the library and archive',
                   'magic': 'the arcane archives'},
 'learn.finding': {'bands': "the star-reader's ridge",
                   'villages': 'the shrine roof at night',
                   'cities': 'the observatory roof',
                   'realms': "the scholar's study",
                   'sail': "the learned society's rooms",
                   'machine': "the firm's laboratory",
                   'modern': 'the lab',
                   'magic': "the artificers' workshop"},
 'prod.wild': {'bands': 'the hunting grounds and weirs',
               'villages': 'the river weir and woods',
               'cities': "the river fishers' boats",
               'realms': 'the fishing harbour',
               'sail': "the fishing banks' fleet",
               'machine': 'the steam trawler',
               'modern': 'the fishing boat',
               'magic': 'the charmed fishing boat'},
 'prod.land': {'bands': 'the wild grain stands',
               'villages': 'the village plots and herd',
               'cities': "the temple estate's fields",
               'realms': "the manor's open fields",
               'sail': 'the enclosed farm',
               'machine': 'the farm and its thresher',
               'modern': 'the family farm',
               'magic': 'the blessed fields'},
 'prod.ground': {'bands': 'the flint bed',
                 'villages': 'the clay pit and woodlot',
                 'cities': 'the royal quarry',
                 'realms': 'the mine in the hills',
                 'sail': 'the coal pit and ironworks',
                 'machine': 'the colliery',
                 'modern': 'the open-cast mine',
                 'magic': 'the ore rift'},
 'prod.craft': {'bands': "the toolmakers' camp",
                'villages': 'the household bench and kiln',
                'cities': 'the palace workshop',
                'realms': 'the guild workshop',
                'sail': 'the cottage loom',
                'machine': 'the back-street workshop',
                'modern': "the maker's workshop",
                'magic': "the artificer's workshop"},
 'prod.works': {'bands': 'the longhouse stores and racks',
                'villages': 'the shared threshing floor',
                'cities': 'the temple workshops',
                'realms': "the lord's mill",
                'sail': 'the shipyard and ironworks',
                'machine': 'the mill',
                'modern': 'the factory floor',
                'magic': "the forge town's furnaces"},
 'prod.founding': {'bands': 'a new camp or crew',
                   'villages': 'a new clearing or kiln',
                   'cities': 'a new barge or workshop',
                   'realms': 'a workshop outside the walls',
                   'sail': 'a new ropewalk or yard',
                   'machine': 'a new works or shop',
                   'modern': "the start-up's rented unit",
                   'magic': 'a new licensed workshop'},
 'comm.gift': {'bands': "the hearth's share-out",
               'villages': 'the harvest feast',
               'cities': "the kin's wedding feast",
               'realms': "the guild's funeral feast",
               'sail': 'the front-room gift table',
               'machine': "the street's whip-round",
               'modern': 'the wedding gift table',
               'magic': "the master's licence feast"},
 'comm.market': {'bands': "the gathering's trading ground",
                 'villages': 'the market at the ford',
                 'cities': 'the gate market',
                 'realms': 'the chartered market square',
                 'sail': 'the exchange and the fair',
                 'machine': 'the covered market',
                 'modern': 'the open-air market',
                 'magic': 'the warded crossroads fair'},
 'comm.shop': {'bands': "the camp's shared stores",
               'villages': "the potter's doorway",
               'cities': 'the stall by the gate',
               'realms': "the chandler's stall",
               'sail': 'the high-street shop',
               'machine': 'the corner shop',
               'modern': 'the supermarket',
               'magic': "the alchemist's shop"},
 'comm.far': {'bands': 'the pass to far traders',
              'villages': "the herders' trading camp",
              'cities': 'the caravan yard',
              'realms': 'the caravanserai',
              'sail': "the merchant house's wharf",
              'machine': 'the goods yard',
              'modern': 'the import house',
              'magic': 'the harbour of spires'},
 'comm.credit': {'bands': "the gift partner's camp",
                 'villages': "the big house's seed pits",
                 'cities': "the temple's loan table",
                 'realms': "the money-changer's bench",
                 'sail': 'the public bank',
                 'machine': 'the savings bank',
                 'modern': 'the bank branch',
                 'magic': 'the warded counting-house'},
 'comm.office': {'bands': 'the fireside count of shares',
                 'villages': "the chief's tally store",
                 'cities': "the scribe's table",
                 'realms': 'the counting room',
                 'sail': 'the counting-house',
                 'machine': "the clerks' office",
                 'modern': 'the office floor',
                 'magic': 'the guild counting-house'},
 'comm.hire': {'bands': "the hunt leader's fire",
               'villages': "the chief's harvest call",
               'cities': "the gate's hiring ground",
               'realms': 'the autumn hiring fair',
               'sail': "a trade's house of call",
               'machine': 'the labour exchange',
               'modern': 'the job centre',
               'magic': "the guild city's hiring hall"},
 'prot.watch': {'bands': "the night fire's watch",
                'villages': 'the gate watch by turns',
                'cities': 'the gate guard',
                'realms': 'the town watch-house',
                'sail': "the constables' watch-house",
                'machine': 'the police station',
                'modern': 'the police station',
                'magic': "the wardens' watch-house"},
 'prot.host': {'bands': 'the war band',
               'villages': "the chief's war band",
               'cities': "the king's levy and barracks",
               'realms': "the lord's muster",
               'sail': 'the standing regiment',
               'machine': 'the conscript army',
               'modern': 'the armed forces',
               'magic': "the Crown's host"},
 'prot.hire': {'bands': 'allies paid in gifts',
               'villages': "the chief's retainers",
               'cities': 'hired foreign spearmen',
               'realms': 'the free company',
               'sail': 'thief-takers and convoy escorts',
               'machine': 'the private guard agency',
               'modern': 'the security firm',
               'magic': 'the free company'},
 'prot.watchers': {'bands': 'the lookout rock',
                   'villages': 'the signal hill',
                   'cities': "the king's eyes and ears",
                   'realms': 'the beacon towers',
                   'sail': "the crown's spy-master",
                   'machine': 'the detective office',
                   'modern': 'the control room',
                   'magic': 'the scrying room'},
 'prot.walls': {'bands': 'the thorn hedge',
                'villages': 'the palisade and ditch',
                'cities': 'the city walls',
                'realms': 'the town walls and towers',
                'sail': 'the star fort',
                'machine': 'the arsenal and street lamps',
                'modern': 'locks, lights and cameras',
                'magic': 'the warded walls'},
 'prot.rescue': {'bands': 'everyone at the grass fire',
                 'villages': 'the bucket line',
                 'cities': 'the night and fire watch',
                 'realms': 'the fire bell and buckets',
                 'sail': "the insurers' fire crew",
                 'machine': 'the fire station',
                 'modern': 'the fire and rescue station',
                 'magic': "the wardens' fire post"},
 'prot.holding': {'bands': 'exile from the band',
                  'villages': 'blood-price and exile',
                  'cities': 'the gaol under the gate',
                  'realms': 'the stocks and the dungeon',
                  'sail': 'the house of correction',
                  'machine': 'the penitentiary',
                  'modern': 'prison and probation',
                  'magic': 'the warded cells'}}
EVENTS = [('feud_settled', 'rule', 'quarrels', False),
 ('law_written', 'rule', 'something_new', False),
 ('new_leader', 'rule', 'a_keeper_passes', True),
 ('favour_exposed', 'rule', 'trust_broken', True),
 ('petition_granted', 'rule', 'the_rule_opens', False),
 ('rising', 'rule', 'power_breaks', True),
 ('reform_wave', 'rule', 'the_rule_opens', False),
 ('restoration', 'rule', 'the_rule_closes', False),
 ('power_seized', 'rule', 'power_breaks', True),
 ('unjust_verdict', 'rule', 'trust_broken', True),
 ('amnesty', 'rule', 'the_rule_opens', False),
 ('new_levy', 'rule', 'the_rule_closes', False),
 ('landmark_ruling', 'rule', 'the_rule_opens', True),
 ('say_widened', 'rule', 'the_rule_opens', False),
 ('rights_narrowed', 'rule', 'the_rule_closes', False),
 ('charter_won', 'rule', 'a_house_opens', False),
 ('deadlock', 'rule', 'power_breaks', True),
 ('false_accusation', 'rule', 'trust_broken', True),
 ('the_count', 'rule', 'something_new', False),
 ('conquest', 'rule', 'war_and_peace', True),
 ('strangers_expelled', 'rule', 'the_rule_closes', False),
 ('bonds_broken', 'rule', 'the_rule_opens', False),
 ('patron_delivers', 'rule', 'names_rise_and_fall', False),
 ('great_feast', 'gather', 'rites_of_life', True),
 ('meeting_place_opens', 'gather', 'a_house_opens', True),
 ('keeper_dies', 'gather', 'a_keeper_passes', True),
 ('brawl', 'gather', 'quarrels', True),
 ('curfew', 'gather', 'the_rule_closes', False),
 ('drink_banned', 'gather', 'the_rule_closes', True),
 ('new_drink_house', 'gather', 'a_house_opens', False),
 ('hall_lost', 'gather', 'a_house_closes', True),
 ('peace_feast', 'gather', 'war_and_peace', False),
 ('slump_shifts', 'gather', 'plenty_and_want', False),
 ('great_fair', 'gather', 'rites_of_life', True),
 ('doors_close', 'gather', 'a_house_closes', False),
 ('informer', 'gather', 'the_rule_closes', False),
 ('evenings_home', 'gather', 'a_house_closes', False),
 ('society_wave', 'gather', 'help_ourselves', False),
 ('the_games', 'gather', 'rites_of_life', True),
 ('rumour_runs', 'gather', 'trust_broken', True),
 ('news_sheet', 'gather', 'something_new', False),
 ('common_ground', 'gather', 'a_house_opens', False),
 ('new_sound', 'arts', 'something_new', True),
 ('scene_sells', 'arts', 'something_new', False),
 ('work_banned', 'arts', 'the_rule_closes', True),
 ('last_teller', 'arts', 'a_keeper_passes', True),
 ('old_songs_return', 'arts', 'help_ourselves', False),
 ('work_of_the_day', 'arts', 'names_rise_and_fall', True),
 ('patron_builds', 'arts', 'a_house_opens', False),
 ('stages_go_dark', 'arts', 'plenty_and_want', False),
 ('new_medium', 'arts', 'something_new', True),
 ('songs_of_war', 'arts', 'war_and_peace', True),
 ('mocking_song', 'arts', 'names_rise_and_fall', True),
 ('local_fame', 'arts', 'names_rise_and_fall', True),
 ('star_falls', 'arts', 'names_rise_and_fall', True),
 ('house_closes', 'arts', 'a_house_closes', True),
 ('far_market', 'arts', 'strangers_come', True),
 ('school_of_arts', 'arts', 'a_house_opens', False),
 ('images_condemned', 'arts', 'the_rule_closes', True),
 ('home_tongue_written', 'arts', 'something_new', True),
 ('benefit_night', 'arts', 'help_ourselves', True),
 ('faith_revival', 'faith', 'rites_of_life', True),
 ('coming_of_age', 'faith', 'rites_of_life', False),
 ('pilgrimage', 'faith', 'rites_of_life', False),
 ('scandal', 'faith', 'trust_broken', True),
 ('new_teaching', 'faith', 'something_new', True),
 ('schism', 'faith', 'power_breaks', True),
 ('faith_outlawed', 'faith', 'the_rule_closes', False),
 ('tolerance', 'faith', 'the_rule_opens', True),
 ('sign', 'faith', 'sickness_and_disaster', True),
 ('rites_cut', 'faith', 'sickness_and_disaster', True),
 ('temple_raised', 'faith', 'a_house_opens', False),
 ('young_drift', 'faith', 'rites_of_life', False),
 ('holy_days', 'faith', 'rites_of_life', False),
 ('calling', 'faith', 'rites_of_life', True),
 ('grove_felled', 'faith', 'the_land', False),
 ('temple_feeds', 'faith', 'plenty_and_want', False),
 ('holy_war', 'faith', 'war_and_peace', True),
 ('succession', 'faith', 'a_keeper_passes', True),
 ('temple_lands_taken', 'faith', 'the_land', False),
 ('marriage_across', 'faith', 'rites_of_life', True),
 ('endowment', 'faith', 'a_house_opens', False),
 ('funeral', 'faith', 'rites_of_life', True),
 ('plague_wave', 'care', 'sickness_and_disaster', True),
 ('quarantine', 'care', 'sickness_and_disaster', False),
 ('neighbours_rush', 'care', 'sickness_and_disaster', True),
 ('laid_up', 'care', 'sickness_and_disaster', True),
 ('remedy_works', 'care', 'something_new', True),
 ('cure_fails', 'care', 'something_new', True),
 ('remedy_feared', 'care', 'something_new', True),
 ('birth_safer', 'care', 'something_new', False),
 ('hard_birth', 'care', 'rites_of_life', True),
 ('healing_dance', 'care', 'rites_of_life', True),
 ('good_death', 'care', 'rites_of_life', False),
 ('house_of_care_opens', 'care', 'a_house_opens', False),
 ('water_clean', 'care', 'a_house_opens', False),
 ('old_ways_fade', 'care', 'a_keeper_passes', False),
 ('sick_club', 'care', 'help_ourselves', False),
 ('old_age_kept', 'care', 'the_rule_opens', False),
 ('care_for_all', 'care', 'the_rule_opens', True),
 ('fees_rise', 'care', 'plenty_and_want', False),
 ('hands_short', 'care', 'plenty_and_want', False),
 ('war_wounded', 'care', 'war_and_peace', True),
 ('healer_famed', 'care', 'names_rise_and_fall', True),
 ('neglect_scandal', 'care', 'trust_broken', True),
 ('knowledge_lost', 'learn', 'a_keeper_passes', True),
 ('lore_rite', 'learn', 'rites_of_life', False),
 ('writing_comes', 'learn', 'something_new', True),
 ('first_school', 'learn', 'a_house_opens', False),
 ('academy_founded', 'learn', 'a_house_opens', True),
 ('print_spreads', 'learn', 'something_new', True),
 ('schools_for_all', 'learn', 'the_rule_opens', True),
 ('the_exam', 'learn', 'rites_of_life', True),
 ('discovery', 'learn', 'something_new', True),
 ('censors_close', 'learn', 'the_rule_closes', True),
 ('learned_leave', 'learn', 'a_house_closes', False),
 ('learned_arrive', 'learn', 'strangers_come', True),
 ('rolls_close', 'learn', 'a_house_closes', False),
 ('free_library', 'learn', 'a_house_opens', True),
 ('teachers_walk_out', 'learn', 'help_ourselves', False),
 ('war_empties_schools', 'learn', 'war_and_peace', True),
 ('glut_of_learned', 'learn', 'a_house_closes', False),
 ('old_ways_taught', 'learn', 'help_ourselves', False),
 ('store_lost', 'learn', 'a_house_closes', True),
 ('taught_at_side', 'learn', 'a_keeper_passes', False),
 ('newcomer_taught', 'learn', 'strangers_come', True),
 ('camp_splits', 'learn', 'a_house_closes', True),
 ('trance_lore_passed', 'learn', 'a_keeper_passes', True),
 ('rich_season', 'prod', 'plenty_and_want', True),
 ('lean_year', 'prod', 'plenty_and_want', True),
 ('new_tool', 'prod', 'something_new', True),
 ('rush', 'prod', 'boom_and_bust', True),
 ('works_close', 'prod', 'boom_and_bust', True),
 ('walkout', 'prod', 'help_ourselves', True),
 ('accident', 'prod', 'sickness_and_disaster', True),
 ('land_taken', 'prod', 'the_land', False),
 ('land_shared', 'prod', 'the_land', True),
 ('stock_fails', 'prod', 'the_land', True),
 ('closed_season', 'prod', 'the_land', False),
 ('scarce_hands', 'prod', 'plenty_and_want', False),
 ('heir', 'prod', 'a_keeper_passes', True),
 ('coop', 'prod', 'help_ourselves', False),
 ('war_works', 'prod', 'war_and_peace', True),
 ('name_won', 'prod', 'names_rise_and_fall', True),
 ('first_fields', 'prod', 'something_new', True),
 ('drift_to_town', 'prod', 'a_house_closes', False),
 ('venture_founded', 'prod', 'a_house_opens', True),
 ('lender_fails', 'comm', 'boom_and_bust', True),
 ('new_route', 'comm', 'boom_and_bust', True),
 ('market_granted', 'comm', 'a_house_opens', False),
 ('dearth', 'comm', 'plenty_and_want', False),
 ('crowd_price', 'comm', 'plenty_and_want', True),
 ('debts_forgiven', 'comm', 'the_rule_opens', True),
 ('licences_few', 'comm', 'a_house_closes', False),
 ('goods_underground', 'comm', 'the_rule_closes', False),
 ('swindle', 'comm', 'boom_and_bust', True),
 ('mania', 'comm', 'boom_and_bust', True),
 ('coin_debased', 'comm', 'boom_and_bust', False),
 ('savings_circle', 'comm', 'help_ourselves', False),
 ('bank_opens', 'comm', 'a_house_opens', False),
 ('big_store', 'comm', 'boom_and_bust', False),
 ('cargo_lost', 'comm', 'boom_and_bust', True),
 ('great_giving', 'comm', 'rites_of_life', True),
 ('newcomers_trade', 'comm', 'strangers_come', True),
 ('new_money', 'comm', 'something_new', False),
 ('hoard_shamed', 'comm', 'plenty_and_want', False),
 ('usury_banned', 'comm', 'the_rule_closes', False),
 ('rents_jump', 'comm', 'plenty_and_want', False),
 ('hiring_fair', 'comm', 'a_house_opens', False),
 ('match_gifts', 'comm', 'rites_of_life', True),
 ('gift_partner_comes', 'comm', 'help_ourselves', True),
 ('seed_lent', 'comm', 'plenty_and_want', True),
 ('raid', 'prot', 'war_and_peace', True),
 ('raid_foiled', 'prot', 'war_and_peace', True),
 ('call_up', 'prot', 'war_and_peace', True),
 ('siege', 'prot', 'war_and_peace', True),
 ('peace_made', 'prot', 'war_and_peace', True),
 ('veterans_home', 'prot', 'war_and_peace', False),
 ('safe_passage', 'prot', 'war_and_peace', False),
 ('new_arms', 'prot', 'something_new', True),
 ('watch_founded', 'prot', 'a_house_opens', False),
 ('crime_wave', 'prot', 'trust_broken', False),
 ('racket', 'prot', 'trust_broken', False),
 ('heavy_hand', 'prot', 'the_rule_closes', True),
 ('crackdown', 'prot', 'the_rule_closes', True),
 ('neighbours_watch', 'prot', 'help_ourselves', False),
 ('walls_and_lamps', 'prot', 'a_house_opens', False),
 ('prison_reform', 'prot', 'the_rule_opens', False),
 ('unpaid_swords', 'prot', 'power_breaks', False),
 ('civil_war', 'prot', 'power_breaks', True),
 ('files_opened', 'prot', 'power_breaks', True),
 ('feud', 'prot', 'quarrels', True),
 ('brave_stand', 'prot', 'names_rise_and_fall', True),
 ('disaster_strikes', 'prot', 'sickness_and_disaster', True),
 ('barrier_fails', 'prot', 'sickness_and_disaster', True)]
