# Chroma Library: dreams, passions and plans, for engine v7 (Library thread, 2026-10-05).
# FINAL: approved by Emren 2026-10-06 22:19 UTC ("fine", Library thread). Rechecked that night: colors even per world,
# timeless setting, safety limits. The engine reads it in place of library.py's seed DREAM_TRIGGERS.
# 2026-10-06 23:00: child and teen stages opened on 21 fitting dreams (and the young-adult gap closed on 4; two magic careers open to elders, the one stage and domain with none) (engine 22:50: child dreams of partner, children,
# community and faith, and teen dreams of community, had no entry to be named by). Stages only; colors unchanged.
# Asked for by the engine thread (05:20): the real spark lists per world, and a catalogue of concrete dreams, for
# modern Earth ("earth"), a tribal world ("tribal": clans, hunts, elders and the turning seasons, before cities) and a
# magic world ("magic": towers, guilds and old powers; a gift may awaken). Plain data: nothing is imported.
#
# DREAM_TRIGGERS[world]: what can spark a dream. Each item is the engine's seed tuple plus a seventh field:
#   (name, source, weight by stage (child, juvenile, young_adult, adult, mature, elder), shows, say)
#   source: family, circle, story, spectacle or stranger.
#   shows: "" when the spark shows whatever the person or story stands for (the engine draws it per source), or a
#     mild color tilt in option format ("W.3 R.2") when the spark itself leans one way. Every tilt sums to .5, and over
#     each world the tilts add up to the same weight for every color.
#   say: one narration line for the game, third person, with {N} for the character.
# DREAMS: concrete dreams the engine names a dream by (the nearest entry in colors, domain, world and stage):
#   name     what the dream is, as a short phrase
#   means    its colors in option format ("G.5 U.5"): the ways of acting the dream is made of
#   domain   career, partner, children, community, faith or pursuit
#   stages   where it can start (space-separated stage names)
#   worlds   the worlds it belongs to ("earth tribal magic" for shared ones)
#   passion  its name once sealed by a rite
#   plan     a five-year plan phrase
#   life     a life-goal phrase
# Per world: four dreams for each single color, two for each of the ten pairs (ally and enemy alike), one for each of
# the ten three-color groups (center color .4), so the means add up evenly for every color, and every domain holds
# all five colors. Magic exists only in the magic world: a dream that needs it says it needs a gift to awaken.

STAGES = ("child", "juvenile", "young_adult", "adult", "mature", "elder")

DREAM_TRIGGERS = {
  "earth": [
    # people in the family
    ("a parent or relative at their work",   "family",    (1.0, 0.6, 0.3, 0.1, 0.1, 0.1), "",
     "{N} spends a day at work with a parent and watches them do the thing they are good at"),
    ("an older sibling or cousin",           "family",    (0.7, 0.6, 0.3, 0.1, 0.0, 0.0), "",
     "an older cousin comes home full of a new life, and {N} hangs on every word"),
    ("a grandparent's stories of the old days", "family", (0.5, 0.4, 0.2, 0.1, 0.2, 0.3), "",
     "a grandparent tells of the old days, and {N} listens until the tea goes cold"),
    ("a grandmother's garden",               "family",    (0.6, 0.5, 0.3, 0.1, 0.1, 0.1), "G.4 W.1",
     "{N} kneels in a grandmother's garden, hands in the soil, and is completely happy"),
    ("a relative who runs their own shop",   "family",    (0.4, 0.5, 0.5, 0.3, 0.2, 0.1), "B.2 W.3",
     "{N} helps out in a relative's shop and watches them count the till, pleased with the day"),
    # people around them
    ("a teacher or coach",                   "circle",    (0.5, 0.8, 0.5, 0.2, 0.1, 0.1), "",
     "a teacher stays after class to show {N} something, and it lights a fire"),
    ("a friend's family",                    "circle",    (0.4, 0.5, 0.3, 0.2, 0.2, 0.1), "",
     "at a friend's house {N} sees a family that lives differently, and likes it"),
    ("someone they meet",                    "circle",    (0.2, 0.4, 0.6, 0.6, 0.5, 0.4), "",
     "{N} meets someone whose life seems to fit them like a glove, and wonders"),
    ("a firefighter visiting school",        "circle",    (0.7, 0.4, 0.0, 0.0, 0.0, 0.0), "W.3 R.2",
     "a firefighter visits the school and lets {N} sit up in the cab of the engine"),
    ("the chess club",                       "circle",    (0.5, 0.6, 0.5, 0.1, 0.1, 0.3), "U.3 B.2",
     "at the chess club a quiet player beats {N} in twelve moves, then shows how"),
    ("a neighbour's workshop in the shed",   "circle",    (0.5, 0.6, 0.4, 0.2, 0.1, 0.1), "U.4 R.1",
     "a neighbour lets {N} watch him take an engine apart in his shed and put it back together"),
    ("the scout troop",                      "circle",    (0.3, 0.8, 0.3, 0.0, 0.0, 0.0), "W.3 G.2",
     "on a first scout camp {N} keeps the fire going all night with the others"),
    # books, films and shows
    ("a book",                               "story",     (0.5, 0.7, 0.6, 0.5, 0.5, 0.5), "",
     "{N} reads a book late into the night and wakes up wanting that life"),
    ("a film or a show",                     "story",     (0.7, 0.8, 0.6, 0.5, 0.4, 0.4), "",
     "the credits roll, and {N} sits very still, already living it"),
    ("a video game",                         "story",     (0.6, 0.8, 0.4, 0.2, 0.1, 0.0), "",
     "{N} plays the same game for a week and starts dreaming in it"),
    ("the news",                             "story",     (0.1, 0.3, 0.4, 0.4, 0.4, 0.4), "",
     "a story on the news stays with {N} for days"),
    ("a nature documentary",                 "story",     (0.4, 0.5, 0.3, 0.3, 0.2, 0.1), "G.3 U.2",
     "{N} watches a documentary about whales and asks a hundred questions"),
    ("a rags-to-riches story",               "story",     (0.4, 0.5, 0.4, 0.2, 0.1, 0.2), "B.3 R.2",
     "{N} reads how someone with nothing built a fortune, and reads it again"),
    # public events
    ("a parade or a festival",               "spectacle", (0.6, 0.4, 0.3, 0.2, 0.2, 0.2), "",
     "a parade passes and {N} cannot look away"),
    ("a match or a contest",                 "spectacle", (0.5, 0.6, 0.4, 0.2, 0.1, 0.1), "",
     "the crowd roars at the final whistle, and {N} roars with it"),
    ("a ceremony",                           "spectacle", (0.3, 0.3, 0.3, 0.3, 0.3, 0.3), "",
     "at a ceremony, standing very still, {N} feels part of something bigger"),
    ("a street protest",                     "spectacle", (0.3, 0.6, 0.7, 0.4, 0.4, 0.3), "R.3 W.2",
     "a street protest goes by, all banners and chanting, and {N} feels their heart pound"),
    ("a concert",                            "spectacle", (0.4, 0.7, 0.4, 0.2, 0.1, 0.1), "R.2 B.3",
     "{N} stands in the crowd at a concert, the bass in their chest, and wants to be up there"),
    ("a wedding in the family",              "spectacle", (0.4, 0.5, 0.7, 0.4, 0.3, 0.4), "W.2 G.3",
     "at a wedding in the family {N} watches two people promise each other everything"),
    # strangers
    ("a stranger passing through",           "stranger",  (0.2, 0.2, 0.3, 0.3, 0.3, 0.3), "",
     "a stranger at the bus stop tells {N} one sentence about their life, and it sticks"),
    ("a stranger stepping out of an expensive car", "stranger", (0.5, 0.5, 0.3, 0.2, 0.2, 0.0), "B.4 R.1",
     "a stranger steps out of a gleaming car across the street, and {N} wants that"),
    ("a doctor in the emergency room",       "stranger",  (0.4, 0.5, 0.4, 0.2, 0.2, 0.1), "U.5",
     "a doctor stitches {N} up after a fall, calmly explaining every step"),
    ("a backpacker at the station",          "stranger",  (0.4, 0.6, 0.4, 0.1, 0.1, 0.1), "R.3 G.2",
     "a backpacker at the station shows {N} a map covered in pins"),
  ],
  "tribal": [
    # people in the family
    ("a parent at the day's work",           "family",    (1.0, 0.6, 0.3, 0.1, 0.1, 0.1), "",
     "{N} follows a parent out at dawn and watches how they read the ground"),
    ("an older brother, sister or cousin",   "family",    (0.7, 0.6, 0.3, 0.1, 0.0, 0.0), "",
     "an older cousin comes back from a long journey, taller somehow, and {N} follows them everywhere"),
    ("the old one they are named after",     "family",    (0.6, 0.5, 0.3, 0.2, 0.1, 0.1), "",
     "{N} sits beside the old one they were named for and wonders what else they share"),
    ("an older cousin's first hunt",         "family",    (0.8, 0.9, 0.1, 0.0, 0.0, 0.0), "G.3 R.2",
     "an older cousin comes back from a first hunt with the marks on their arms, and {N} cannot look away"),
    ("a grandmother who knows every plant",  "family",    (0.6, 0.5, 0.3, 0.3, 0.3, 0.2), "G.3 U.2",
     "a grandmother names every plant on the path for {N}, and what each one is for"),
    ("a new baby in the family",             "family",    (0.4, 0.5, 0.5, 0.1, 0.1, 0.1), "W.2 G.3",
     "a new baby is born in the family, and {N} is allowed to hold it"),
    # people around them
    ("the elder who teaches the children",   "circle",    (0.5, 0.8, 0.5, 0.2, 0.1, 0.1), "",
     "the elder who teaches the children picks {N} for a task, and {N} glows"),
    ("a friend's family at their fire",      "circle",    (0.4, 0.5, 0.3, 0.2, 0.2, 0.1), "",
     "at a friend's fire {N} sees a family that does things another way"),
    ("someone met at a gathering of the clans", "circle", (0.2, 0.4, 0.6, 0.6, 0.5, 0.4), "",
     "at the gathering of the clans {N} meets someone whose life is nothing like their own"),
    ("the best tracker in the band",         "circle",    (0.3, 0.8, 0.5, 0.2, 0.0, 0.0), "U.3 G.2",
     "the best tracker in the band reads a whole night's story in the dust for {N}"),
    ("the hunt leader sharing out the meat", "circle",    (0.6, 0.8, 0.3, 0.1, 0.1, 0.0), "W.3 B.2",
     "the hunt leader shares out the meat, a fair piece to every fire, and {N} sees that nobody argues"),
    ("a young hunter wearing a lion's claws", "circle",   (0.4, 0.6, 0.4, 0.2, 0.0, 0.0), "B.3 R.2",
     "a young hunter walks into camp wearing a lion's claws, and {N} sees everyone stop talking"),
    ("an old toolmaker at work",             "circle",    (0.7, 0.7, 0.3, 0.1, 0.1, 0.1), "U.4 W.1",
     "{N} watches an old toolmaker strike a long blade from a stone with one perfect blow"),
    # stories and songs
    ("a storyteller at the fire",            "story",     (0.7, 0.8, 0.6, 0.5, 0.5, 0.5), "",
     "a storyteller at the fire tells of a woman who walked to the edge of the world, and {N} cannot sleep"),
    ("an old song about an ancestor",        "story",     (0.5, 0.6, 0.5, 0.4, 0.4, 0.4), "",
     "the old ones sing of an ancestor's deeds, and {N} learns every word"),
    ("a dream the elders call a sign",       "story",     (0.4, 0.5, 0.4, 0.3, 0.3, 0.3), "",
     "{N} dreams of something strange, and the elders say it points to a path"),
    ("tales of the trickster",               "story",     (0.6, 0.5, 0.3, 0.2, 0.4, 0.3), "B.3 U.2",
     "the tale of the trickster who fooled the lion makes {N} laugh for days"),
    ("the paintings in the deep cave",       "story",     (0.5, 0.5, 0.5, 0.4, 0.5, 0.3), "R.3 G.2",
     "deep in the cave, by torchlight, {N} sees the painted horses move"),
    # gatherings and rites
    ("the feast after a great hunt",         "spectacle", (0.6, 0.4, 0.3, 0.2, 0.2, 0.2), "",
     "after a great hunt the whole camp feasts, and {N} watches who is praised"),
    ("a naming or coming-of-age rite",       "spectacle", (0.3, 0.3, 0.3, 0.3, 0.3, 0.3), "",
     "at a rite by firelight {N} feels the whole clan close around them"),
    ("the great gathering at the waterhole", "spectacle", (0.5, 0.6, 0.5, 0.3, 0.2, 0.2), "",
     "at the great gathering by the waterhole {N} sees more people than they knew there were"),
    ("the great herds crossing the river",   "spectacle", (0.6, 0.5, 0.3, 0.3, 0.3, 0.3), "",
     "the great herds cross the river for a whole day, and {N} watches every one"),
    ("a wrestling match at the gathering",   "spectacle", (0.4, 0.7, 0.4, 0.1, 0.0, 0.0), "R.3 B.2",
     "at the gathering two wrestlers strain until one is thrown, and {N} shouts until hoarse"),
    ("the elders settling a quarrel",        "spectacle", (0.4, 0.6, 0.4, 0.3, 0.2, 0.1), "W.3 U.2",
     "the elders sit with a bitter quarrel until it is settled, and {N} watches how they do it"),
    ("the healers' all-night dance",         "spectacle", (0.6, 0.6, 0.3, 0.2, 0.2, 0.2), "R.3 W.2",
     "the healers dance all night until the spirits come, and {N} cannot stop watching"),
    # strangers
    ("a stranger from beyond the hills",     "stranger",  (0.2, 0.2, 0.3, 0.3, 0.3, 0.3), "",
     "a stranger from beyond the hills sits by {N} at the fire one night and is gone by morning"),
    ("a wanderer who has seen the sea",      "stranger",  (0.3, 0.6, 0.6, 0.3, 0.2, 0.2), "",
     "a wanderer who has walked to the sea tells {N} about water that never ends"),
    ("a visiting trader",                    "stranger",  (0.6, 0.7, 0.4, 0.3, 0.3, 0.2), "B.3 W.2",
     "a trader arrives with shells from the far sea, and {N} pushes through the crowd to watch the bargaining"),
  ],
  "magic": [
    # people in the family
    ("a parent at their post",               "family",    (1.0, 0.6, 0.3, 0.1, 0.1, 0.1), "",
     "{N} spends a day at a parent's post and watches the work they are known for"),
    ("an older cousin home from an apprenticeship", "family", (0.7, 0.6, 0.3, 0.1, 0.0, 0.0), "",
     "an older cousin comes home from an apprenticeship with new words and new hands, and {N} wants the same"),
    ("a cousin whose gift awakens",          "family",    (0.5, 0.7, 0.4, 0.1, 0.0, 0.0), "",
     "a cousin lights a candle without touching it, and {N} stares"),
    ("a grandmother's charms and herbs",     "family",    (0.8, 0.4, 0.2, 0.2, 0.2, 0.1), "G.3 U.2",
     "a grandmother shows {N} which herb to hang over the door, and why"),
    # people around them
    ("a tutor or a master",                  "circle",    (0.5, 0.8, 0.5, 0.2, 0.1, 0.1), "",
     "a tutor keeps {N} after the lesson to show them something that is not in the book"),
    ("a friend's family",                    "circle",    (0.4, 0.5, 0.3, 0.2, 0.2, 0.1), "",
     "at a friend's house {N} sees a family that lives by other ways"),
    ("someone met at the inn",               "circle",    (0.2, 0.4, 0.6, 0.6, 0.5, 0.4), "",
     "at the inn {N} falls into talk with a traveller whose life is nothing like their own"),
    ("an alchemist's workshop",              "circle",    (0.6, 0.5, 0.4, 0.3, 0.4, 0.0), "U.3 R.2",
     "in an alchemist's workshop something bangs, smokes and turns gold, and {N} laughs out loud"),
    ("the old druid of the grove",           "circle",    (0.4, 0.6, 0.5, 0.3, 0.2, 0.0), "G.3 W.2",
     "the old druid of the grove lets {N} sit with him while the trees are quiet"),
    ("a temple healer at a sickbed",         "circle",    (0.4, 0.5, 0.4, 0.5, 0.6, 0.5), "W.3 G.2",
     "a temple healer sits all night with a sick neighbour, and in the morning {N} hears the fever has broken"),
    # books, ballads and shows
    ("a book from the old library",          "story",     (0.5, 0.7, 0.6, 0.5, 0.5, 0.5), "",
     "{N} reads a book from the old library by candlelight and wakes up wanting that life"),
    ("a bard's ballad at the inn",           "story",     (0.6, 0.8, 0.6, 0.4, 0.4, 0.4), "",
     "a bard at the inn sings of an old hero, and {N} knows the song by heart by morning"),
    ("a puppet show at the fair",            "story",     (0.8, 0.5, 0.1, 0.1, 0.1, 0.1), "",
     "at the fair a puppet show plays out a whole adventure, and {N} watches it three times"),
    ("a sealed book of spells",              "story",     (0.4, 0.5, 0.4, 0.5, 0.4, 0.6), "U.3 B.2",
     "{N} finds an old book of spells in the attic, half of it in a script nobody can read"),
    # public events
    ("the harvest festival",                 "spectacle", (0.6, 0.4, 0.3, 0.2, 0.2, 0.2), "",
     "at the harvest festival the whole town dances, and {N} watches who leads it"),
    ("a tournament",                         "spectacle", (0.5, 0.6, 0.4, 0.2, 0.1, 0.1), "",
     "at the tournament a rider breaks a lance and the crowd roars, and {N} roars with it"),
    ("a rite at the temple",                 "spectacle", (0.3, 0.3, 0.3, 0.3, 0.3, 0.3), "",
     "at a rite in the temple, among the candles, {N} feels part of something very old"),
    ("a guild procession",                   "spectacle", (0.6, 0.6, 0.4, 0.2, 0.2, 0.2), "W.3 B.2",
     "the guild procession passes in silk and gold, banners high, and {N} cannot look away"),
    ("a duel seen from a window",            "spectacle", (0.4, 0.6, 0.6, 0.3, 0.1, 0.1), "R.3 U.2",
     "from a window {N} watches two mages duel in the square, light against fire"),
    ("a knight of the Order riding through", "spectacle", (0.7, 0.4, 0.3, 0.2, 0.0, 0.0), "W.3 R.2",
     "a knight of the Order rides through and stops to help an old man with his cart, and {N} stares after her"),
    ("the trials at the academy",            "spectacle", (0.5, 0.8, 0.4, 0.0, 0.0, 0.0), "U.3 W.2",
     "{N} watches the academy's trials through the gate and sees one pupil pass"),
    ("a merchant prince's barge",            "spectacle", (0.5, 0.5, 0.4, 0.2, 0.1, 0.0), "B.5",
     "a merchant prince's barge comes up the river hung with lanterns, and {N} wants that"),
    ("a dragon over the hills",              "spectacle", (0.6, 0.6, 0.3, 0.3, 0.5, 0.3), "R.3 B.2",
     "a dragon passes high over the hills at dusk, and {N} forgets to breathe"),
    # strangers
    ("a stranger passing through",           "stranger",  (0.2, 0.2, 0.3, 0.3, 0.3, 0.3), "",
     "a cloaked stranger stops at the well, says something odd to {N}, and walks on"),
    ("travellers of the elder folk",         "stranger",  (0.4, 0.5, 0.5, 0.4, 0.3, 0.3), "",
     "travellers of the elder folk stop at the inn for one night, and {N} cannot stop staring"),
    ("a wandering hedge-witch",              "stranger",  (0.6, 0.7, 0.5, 0.2, 0.1, 0.1), "G.3 B.2",
     "a hedge-witch passing through cures a neighbour's goat with a muttered word, names her price, and winks at {N}"),
    ("a ranger at the inn",                  "stranger",  (0.4, 0.6, 0.4, 0.2, 0.2, 0.4), "R.3 G.2",
     "a ranger at the inn talks of the borderlands, mud still on her boots, and {N} hangs on every word"),
  ],
}


DREAMS = [
  # ================= shared by several worlds =================
  # one color
  dict(name="a partner to think with", means="U1", domain="partner", stages="juvenile young_adult adult mature",
       worlds="earth tribal magic", passion="a meeting of minds",
       plan="find someone who can keep up, and never stop talking", life="one conversation that lasts a whole life"),
  dict(name="to marry well", means="B1", domain="partner", stages="child juvenile young_adult",
       worlds="earth tribal magic", passion="making a good match",
       plan="move among the right people and make a match that raises them",
       life="a household that wants for nothing"),
  dict(name="a great love", means="R1", domain="partner", stages="child juvenile young_adult adult mature elder",
       worlds="earth tribal magic", passion="loving with the whole heart",
       plan="find the one and never settle for less", life="to have loved and been loved completely"),
  dict(name="a family of one's own", means="G1", domain="children", stages="child juvenile young_adult adult",
       worlds="earth tribal magic", passion="family life", plan="settle down and have children",
       life="children and grandchildren around the fire or the table"),
  dict(name="to take in a child who has no one", means="W1", domain="children", stages="young_adult adult mature",
       worlds="earth magic", passion="giving children a home", plan="take in a child who needs a home",
       life="a child who had no one, grown up and at home"),
  dict(name="a fortune of one's own", means="B1", domain="pursuit", stages="child juvenile young_adult adult mature",
       worlds="earth magic", passion="making money grow", plan="save hard and put every coin to work",
       life="never to need anyone's money again"),
  dict(name="a garden of one's own", means="G1", domain="pursuit", stages="young_adult adult mature elder",
       worlds="earth magic", passion="the garden", plan="dig and plant a garden on a patch of one's own",
       life="a garden the grandchildren will remember"),
  dict(name="to start a festival the whole town comes to", means="R1", domain="community",
       stages="child juvenile young_adult adult mature elder", worlds="earth magic",
       passion="bringing people together to celebrate",
       plan="get a first festival on its feet and make it come back every year",
       life="a festival that outlives its founder"),
  # two colors
  dict(name="a marriage that lasts a lifetime", means="W.5 G.5", domain="partner",
       stages="child juvenile young_adult adult", worlds="earth tribal magic", passion="keeping faith with one person",
       plan="find the right person and make the vows", life="to grow old side by side, the vows kept"),
  dict(name="a big, noisy family", means="R.5 G.5", domain="children", stages="child juvenile young_adult adult",
       worlds="earth tribal magic", passion="a full house", plan="have children and keep the door open to everyone",
       life="a table too small for everyone who comes"),
  dict(name="to raise children well and teach them all one knows", means="W.5 U.5", domain="children",
       stages="young_adult adult", worlds="earth tribal magic", passion="bringing up children",
       plan="raise children with care and teach them something every day",
       life="children who grow up good and know more than their parents ever did"),
  dict(name="a family name that counts for something", means="B.5 G.5", domain="children",
       stages="young_adult adult mature elder", worlds="earth magic", passion="the family's standing",
       plan="build up what the family has and make the name known",
       life="a name the grandchildren carry with pride"),
  dict(name="a healer", means="W.5 G.5", domain="career", stages="child juvenile young_adult", worlds="tribal magic",
       passion="healing the sick", plan="learn the healer's craft at an old healer's side",
       life="a lifetime of the sick made well"),

  # ================= modern Earth =================
  # one color
  dict(name="a police officer", means="W1", domain="career", stages="child juvenile", worlds="earth",
       passion="keeping the peace", plan="join the police and get through training",
       life="a whole career keeping one town safe"),
  dict(name="a nurse", means="W1", domain="career", stages="child juvenile young_adult", worlds="earth",
       passion="caring for the sick", plan="train as a nurse",
       life="to run a ward where every patient is looked after"),
  dict(name="a life serving one's faith", means="W1", domain="faith",
       stages="child juvenile young_adult adult mature elder", worlds="earth", passion="serving a congregation",
       plan="train for the ministry of one's faith", life="a congregation cared for over a lifetime"),
  dict(name="a scientist", means="U1", domain="career", stages="child juvenile young_adult", worlds="earth",
       passion="finding things out", plan="study science at university", life="a discovery with one's name on it"),
  dict(name="to master the piano", means="U1", domain="pursuit", stages="child juvenile adult mature elder",
       worlds="earth", passion="the piano", plan="practise every day until a first real concert",
       life="to play the hardest pieces without a single slip"),
  dict(name="to speak five languages", means="U1", domain="pursuit",
       stages="juvenile young_adult adult mature elder", worlds="earth", passion="languages",
       plan="become fluent in two new languages", life="to talk with people everywhere in their own tongue"),
  dict(name="a business of one's own", means="B1", domain="career", stages="juvenile young_adult adult mature elder",
       worlds="earth", passion="making deals", plan="start a company and make it pay", life="a business empire"),
  dict(name="to be famous", means="B1", domain="pursuit", stages="child juvenile", worlds="earth",
       passion="being in the spotlight", plan="build a following that grows every year",
       life="a name everyone knows"),
  dict(name="to play in a band", means="R1", domain="pursuit", stages="juvenile young_adult adult", worlds="earth",
       passion="the band", plan="record an album and go on tour", life="a life on the road with the music"),
  dict(name="to travel the world", means="R1", domain="pursuit",
       stages="child juvenile young_adult adult mature elder", worlds="earth", passion="the open road",
       plan="save up and set off for a year on the road", life="to have set foot on every continent"),
  dict(name="a farmer", means="G1", domain="career", stages="child juvenile young_adult", worlds="earth",
       passion="working the land", plan="learn farming and take on a farm",
       life="a farm that feeds the family and the neighbours"),
  dict(name="to keep the family's old faith and hand it on", means="G1", domain="faith", stages="child juvenile young_adult adult mature elder",
       worlds="earth", passion="the family's old faith",
       plan="keep the old feasts and prayers at home and teach them to the young",
       life="a faith handed on unbroken to the grandchildren"),
  # two colors
  dict(name="a doctor", means="W.5 U.5", domain="career", stages="child juvenile young_adult", worlds="earth",
       passion="medicine", plan="get into medical school", life="a lifetime of patients made well"),
  dict(name="a chess grandmaster", means="U.5 B.5", domain="pursuit", stages="child juvenile young_adult",
       worlds="earth", passion="chess", plan="play every tournament and earn a master's title",
       life="to be the grandmaster nobody wants to draw"),
  dict(name="a spy", means="U.5 B.5", domain="career", stages="child juvenile young_adult", worlds="earth",
       passion="secrets", plan="learn languages and join the intelligence service",
       life="to know what nobody else knows"),
  dict(name="a star footballer", means="B.5 R.5", domain="career", stages="child juvenile", worlds="earth",
       passion="football", plan="make the first team of a club",
       life="to play in a final in front of the whole world"),
  dict(name="a racing driver", means="B.5 R.5", domain="career", stages="child juvenile", worlds="earth",
       passion="speed", plan="race in the junior series and get noticed", life="a championship title"),
  dict(name="to climb the highest mountains", means="R.5 G.5", domain="pursuit", stages="child juvenile young_adult",
       worlds="earth", passion="the mountains", plan="climb the great peaks of the high ranges",
       life="to stand on the roof of the world"),
  dict(name="a teacher", means="W.5 G.5", domain="career", stages="child juvenile young_adult", worlds="earth",
       passion="teaching children", plan="train as a teacher", life="generations of pupils who remember them"),
  dict(name="to run the town", means="W.5 B.5", domain="community", stages="child juvenile young_adult adult mature elder",
       worlds="earth", passion="politics", plan="win a seat on the council", life="to be mayor"),
  dict(name="to reach the top of a big firm", means="W.5 B.5", domain="career", stages="juvenile young_adult adult",
       worlds="earth", passion="climbing the ladder", plan="make partner or director by outworking everyone",
       life="to run the whole company"),
  dict(name="an inventor", means="U.5 R.5", domain="career", stages="child juvenile", worlds="earth",
       passion="inventing things", plan="build a prototype and get a patent",
       life="an invention the whole world uses"),
  dict(name="to make video games", means="U.5 R.5", domain="career", stages="juvenile young_adult adult",
       worlds="earth", passion="making games", plan="make a first game and get it out", life="a game millions play"),
  dict(name="to live off the land, owing nothing to anyone", means="B.5 G.5", domain="pursuit",
       stages="young_adult adult mature elder", worlds="earth", passion="living off the land",
       plan="buy a plot of wild land and learn to live from it", life="a homestead that needs nothing from anyone"),
  dict(name="a firefighter", means="W.5 R.5", domain="career", stages="child juvenile", worlds="earth",
       passion="fighting fires", plan="join the fire brigade", life="a lifetime of rescues"),
  dict(name="to fight for a cause", means="W.5 R.5", domain="faith",
       stages="juvenile young_adult adult mature elder", worlds="earth", passion="the cause",
       plan="organise a campaign that changes a law", life="to see the cause win"),
  dict(name="a vet", means="G.5 U.5", domain="career", stages="child juvenile young_adult", worlds="earth",
       passion="caring for animals", plan="train as a vet", life="a practice of one's own"),
  dict(name="to know every bird by its song", means="U.5 G.5", domain="pursuit",
       stages="child juvenile adult mature elder", worlds="earth", passion="birdwatching",
       plan="see and name every bird in the country",
       life="a lifetime's list of birds, every one seen with one's own eyes"),
  # three colors
  dict(name="to make one's town a green and fair place to live", means="W.4 U.3 G.3", domain="community",
       stages="juvenile young_adult adult mature elder", worlds="earth", passion="making the town better",
       plan="win the fight for a new park and fair rents on the council's planning board",
       life="a town that is green, fair and good to grow up in"),
  dict(name="an architect", means="U.4 W.3 B.3", domain="career", stages="juvenile young_adult", worlds="earth",
       passion="designing buildings", plan="qualify as an architect",
       life="a skyline with one's own buildings in it"),
  dict(name="to found a movement of one's own", means="B.4 U.3 R.3", domain="faith",
       stages="juvenile young_adult adult mature", worlds="earth", passion="the movement",
       plan="write the manifesto and win the first thousand followers",
       life="a movement that changes how people live"),
  dict(name="a prize fighter", means="R.4 B.3 G.3", domain="career", stages="child juvenile young_adult",
       worlds="earth", passion="fighting in the ring", plan="turn professional and win the first ten fights",
       life="a title belt"),
  dict(name="an animal sanctuary", means="G.4 W.3 R.3", domain="pursuit",
       stages="child juvenile young_adult adult mature elder", worlds="earth", passion="rescued animals",
       plan="buy a smallholding and open a sanctuary", life="a sanctuary where no animal is turned away"),
  dict(name="to build up the family firm", means="B.4 W.3 G.3", domain="career", stages="juvenile young_adult adult",
       worlds="earth", passion="the family business", plan="take over the family firm and grow it",
       life="a firm handed on, bigger, to the next generation"),
  dict(name="a black belt", means="R.4 U.3 W.3", domain="pursuit", stages="child juvenile", worlds="earth",
       passion="martial arts", plan="train every day for the black belt", life="a school of one's own"),
  dict(name="to breed champion horses", means="G.4 U.3 B.3", domain="pursuit", stages="child juvenile adult",
       worlds="earth", passion="breeding horses", plan="raise a first foal that wins",
       life="a bloodline known everywhere"),
  dict(name="an officer in the army", means="W.4 B.3 R.3", domain="career", stages="child juvenile young_adult",
       worlds="earth", passion="the army", plan="get through officer training", life="to command a regiment"),
  dict(name="an explorer", means="U.4 R.3 G.3", domain="pursuit", stages="child juvenile young_adult",
       worlds="earth", passion="exploring wild places", plan="join an expedition to the far north",
       life="to map a place nobody has mapped"),

  # ================= the tribal world =================
  # one color
  dict(name="a guardian of the camp", means="W1", domain="career", stages="child juvenile young_adult",
       worlds="tribal", passion="keeping watch over the camp",
       plan="learn every path a raider or a lion could come by", life="a camp never once taken by surprise"),
  dict(name="the keeper of the camp's fire", means="W1", domain="career", stages="child juvenile", worlds="tribal",
       passion="tending the fire", plan="learn to carry fire from camp to camp without losing it",
       life="a fire that never went out in a lifetime"),
  dict(name="to keep the clan's rites", means="W1", domain="faith", stages="child juvenile young_adult adult mature",
       worlds="tribal", passion="the rites of the clan",
       plan="learn every rite and every chant, word for word, from the old rite-keeper",
       life="to lead the rites when the old ones are gone"),
  dict(name="the best toolmaker in the clans", means="U1", domain="career", stages="child juvenile young_adult",
       worlds="tribal", passion="knapping stone", plan="learn to strike the long blades the old masters make",
       life="blades traded as far as the sea"),
  dict(name="to know the name of every star", means="U1", domain="pursuit", stages="child mature elder",
       worlds="tribal", passion="watching the stars", plan="learn the paths of the stars through every season",
       life="to know the sky as well as the land"),
  dict(name="to know what the old stories really mean", means="U1", domain="faith",
       stages="child juvenile young_adult adult mature elder", worlds="tribal",
       passion="the hidden meaning of the stories",
       plan="sit with every old storyteller and ask what each story is for",
       life="to understand what the ancestors knew"),
  dict(name="a trader between the clans", means="B1", domain="career", stages="juvenile young_adult adult mature",
       worlds="tribal", passion="trading", plan="carry goods between the camps and drive a hard bargain in each",
       life="the richest store of beads, shells and furs in the clans"),
  dict(name="to be owed a favour in every camp", means="B1", domain="pursuit",
       stages="young_adult adult mature elder", worlds="tribal", passion="giving gifts that are remembered",
       plan="make a gift-partner in every camp, and always give a little more than one gets",
       life="a welcome, and a debt, waiting at every fire"),
  dict(name="to be the name told at every fire", means="B1", domain="pursuit", stages="child juvenile",
       worlds="tribal", passion="being talked about", plan="do what no one else dares, and make sure it is told",
       life="a name the clans still tell when one is gone"),
  dict(name="a wandering singer", means="R1", domain="career", stages="child juvenile young_adult", worlds="tribal",
       passion="singing", plan="learn the songs of every clan and walk between them",
       life="a song of one's own sung at every fire"),
  dict(name="to see the great sea", means="R1", domain="pursuit", stages="juvenile young_adult adult mature elder",
       worlds="tribal", passion="wandering far", plan="walk west with the traders until the land ends",
       life="to stand at the edge of the great water"),
  dict(name="to lead the songs at every feast", means="R1", domain="community", stages="child juvenile young_adult adult",
       worlds="tribal", passion="the feast songs", plan="learn every dance and start the singing at each feast",
       life="feasts that do not begin until one arrives"),
  dict(name="a hunter who feeds the clan", means="G1", domain="career", stages="child juvenile", worlds="tribal",
       passion="the hunt", plan="learn to track and hunt beside the old hunters",
       life="a lifetime of meat brought home to the fires"),
  dict(name="to keep the band together through the hard seasons", means="G1", domain="community",
       stages="juvenile young_adult adult mature", worlds="tribal", passion="the band and its families",
       plan="keep the old ways of sharing when the food runs short",
       life="a band that never broke apart, however hard the winter"),
  dict(name="to walk the lands of the ancestors", means="G1", domain="pursuit", stages="mature elder",
       worlds="tribal", passion="the old lands", plan="walk to every place the ancestors camped, one each season",
       life="to know the land as the ancestors knew it"),
  dict(name="a grandmother or grandfather to the whole camp", means="W1", domain="children", stages="mature elder",
       worlds="tribal", passion="the camp's children",
       plan="help raise the grandchildren and gather food for the young families",
       life="a camp full of children who call them grandmother or grandfather"),
  # two colors
  dict(name="a bonesetter", means="W.5 U.5", domain="career", stages="juvenile young_adult adult", worlds="tribal",
       passion="mending the hurt", plan="learn to set bones and close wounds from the old bonesetter",
       life="a lifetime of the hurt made whole"),
  dict(name="as clever as the trickster in the tales", means="U.5 B.5", domain="pursuit", stages="child juvenile",
       worlds="tribal", passion="outwitting everyone", plan="win every game of wits and riddles at the gatherings",
       life="to be the one the new trickster tales are told about"),
  dict(name="a scout who knows every clan's business", means="U.5 B.5", domain="career",
       stages="child juvenile young_adult", worlds="tribal", passion="watching unseen",
       plan="go out alone to watch the far camps and come back with news",
       life="to know every clan's mind before it acts"),
  dict(name="the champion wrestler of the gatherings", means="B.5 R.5", domain="pursuit", stages="child juvenile",
       worlds="tribal", passion="wrestling", plan="throw every wrestler of one's own age at the gatherings",
       life="never once to be thrown"),
  dict(name="the fastest runner in the clans", means="B.5 R.5", domain="pursuit", stages="child juvenile",
       worlds="tribal", passion="running", plan="outrun every runner at the gathering",
       life="a name for speed that the clans remember"),
  dict(name="to raise a wolf cub", means="R.5 G.5", domain="pursuit", stages="child juvenile", worlds="tribal",
       passion="the wolves", plan="find an orphaned cub and raise it by the fire",
       life="a wolf that walks beside them for life"),
  dict(name="to speak for the clan at the gatherings", means="W.5 B.5", domain="community",
       stages="child juvenile young_adult adult mature elder", worlds="tribal", passion="speaking for the clan",
       plan="earn the trust of the elders and a place at the council fire",
       life="a voice the other clans listen for"),
  dict(name="a hunt leader", means="W.5 B.5", domain="career", stages="child juvenile young_adult adult",
       worlds="tribal", passion="leading the hunt", plan="lead a hunt of one's own and share the meat fairly",
       life="to lead the great hunts for a generation"),
  dict(name="a new way of hunting that nobody has tried", means="U.5 R.5", domain="career",
       stages="juvenile young_adult adult mature", worlds="tribal", passion="trying new ways",
       plan="make a new kind of trap and prove it works", life="a way of hunting the whole clan uses"),
  dict(name="to build a boat that crosses the great lake", means="U.5 R.5", domain="pursuit",
       stages="juvenile young_adult adult", worlds="tribal", passion="boat-building",
       plan="build a boat and cross the lake in it", life="to reach the far shore that nobody has seen"),
  dict(name="to found a clan of one's own", means="B.5 G.5", domain="children", stages="juvenile young_adult adult",
       worlds="tribal", passion="one's own line", plan="take a partner, have children and make a camp of one's own",
       life="to be the ancestor of a clan"),
  dict(name="to speak with the spirits of the dead", means="B.5 G.5", domain="faith",
       stages="juvenile young_adult adult mature elder", worlds="tribal", passion="the spirits of the dead",
       plan="learn from the old spirit-talker how to call the dead and ask what they know",
       life="to be the one the clan comes to when it needs the counsel of the dead"),
  dict(name="a trance-dancer who heals", means="W.5 R.5", domain="faith", stages="child juvenile young_adult",
       worlds="tribal", passion="the healing dance",
       plan="dance with the healers every night until the spirits come",
       life="to heal the whole camp with the dance"),
  dict(name="a runner who carries news between the camps", means="W.5 R.5", domain="career", stages="child juvenile",
       worlds="tribal", passion="running the long paths",
       plan="learn every path between the camps and carry the clan's messages",
       life="to be the one every camp trusts with its news"),
  dict(name="a gatherer who knows every plant", means="U.5 G.5", domain="career",
       stages="child juvenile young_adult", worlds="tribal", passion="plant lore",
       plan="learn every plant's use and season from the grandmothers",
       life="to know what grows where, and when, better than anyone living"),
  dict(name="a tracker who can read any trail", means="U.5 G.5", domain="career", stages="child juvenile",
       worlds="tribal", passion="tracking", plan="learn to read every track in dust, mud and snow",
       life="to read any trail, however old"),
  # three colors
  dict(name="an elder whose counsel the clans seek", means="W.4 U.3 G.3", domain="community",
       stages="adult mature elder", worlds="tribal", passion="giving counsel",
       plan="listen more than one speaks, and learn every family's story",
       life="to settle quarrels with a word, as the old ones did"),
  dict(name="the one who reads the seasons for the clan", means="U.4 W.3 B.3", domain="career",
       stages="juvenile young_adult adult", worlds="tribal", passion="reading the seasons",
       plan="learn the signs of the moons and the herds until one's word decides when the camp moves",
       life="the voice the whole clan waits for before it moves"),
  dict(name="to cross the mountains and come back rich", means="B.4 U.3 R.3", domain="pursuit",
       stages="juvenile young_adult adult", worlds="tribal", passion="far trading",
       plan="travel past the mountains with goods nobody there has seen",
       life="to come home with riches no one in the clans has seen"),
  dict(name="to bring down a mammoth", means="R.4 B.3 G.3", domain="pursuit", stages="child juvenile young_adult",
       worlds="tribal", passion="the great hunt", plan="join the mammoth hunters and earn a place at the front",
       life="a mammoth brought down by one's own spear"),
  dict(name="a storyteller at the fire", means="G.4 W.3 R.3", domain="career",
       stages="juvenile young_adult adult mature elder", worlds="tribal", passion="telling stories",
       plan="learn the old stories from the elders and tell them at night",
       life="stories still told long after one is gone"),
  dict(name="to hold the family's waterhole for the generations", means="B.4 W.3 G.3", domain="pursuit",
       stages="young_adult adult mature elder", worlds="tribal", passion="the family's waterhole",
       plan="keep the family's right to the waterhole through every season and quarrel",
       life="a waterhole the grandchildren still call their own"),
  dict(name="to master the spear-thrower", means="R.4 U.3 W.3", domain="pursuit", stages="child juvenile",
       worlds="tribal", passion="the spear-thrower", plan="practise every day until no throw misses",
       life="a throw the clans still talk about"),
  dict(name="a maker of arrow poison for the hunt", means="G.4 U.3 B.3", domain="career",
       stages="juvenile young_adult", worlds="tribal", passion="the poison lore of the hunt",
       plan="learn from the old poison-maker which beetles and roots to use",
       life="arrows that can bring down any beast"),
  dict(name="a war leader who keeps the raiders away", means="W.4 B.3 R.3", domain="career",
       stages="juvenile young_adult adult", worlds="tribal", passion="leading the defence of the clan",
       plan="become the fighter the others follow when raiders come", life="a clan no raider dares to attack"),
  dict(name="to find the herds' hidden winter grounds", means="U.4 R.3 G.3", domain="pursuit",
       stages="child juvenile young_adult", worlds="tribal", passion="following the herds",
       plan="follow the herds alone past the known lands", life="to find the place where the herds go in winter"),

  # ================= the magic world =================
  # one color
  dict(name="a knight of the Order", means="W1", domain="career", stages="child juvenile young_adult",
       worlds="magic", passion="the knightly vows", plan="serve a knight of the Order as squire",
       life="to be knighted and keep every vow"),
  dict(name="a town warden", means="W1", domain="career", stages="child juvenile young_adult", worlds="magic",
       passion="keeping the town safe", plan="join the town wardens", life="to be captain of the wardens"),
  dict(name="a priest of the temple", means="W1", domain="faith", stages="child juvenile young_adult adult mature elder",
       worlds="magic", passion="serving the temple", plan="enter the temple as a novice",
       life="a lifetime of rites kept and people comforted"),
  dict(name="a mage", means="U1", domain="career", stages="child juvenile young_adult", worlds="magic",
       passion="the study of magic (once a gift awakens)", plan="pass the academy's trials (needs a gift to awaken)",
       life="a seat among the masters of the high tower"),
  dict(name="a scholar of the arcane archives", means="U1", domain="career", stages="juvenile young_adult adult mature elder",
       worlds="magic", passion="the arcane archives", plan="win an apprenticeship in the arcane archives",
       life="to write the book the archives are known for"),
  dict(name="to read every book in the great library", means="U1", domain="pursuit",
       stages="child juvenile young_adult mature elder", worlds="magic", passion="reading",
       plan="read the great library shelf by shelf", life="to have read every book in the great library"),
  dict(name="a merchant prince", means="B1", domain="career", stages="juvenile young_adult", worlds="magic",
       passion="trading", plan="win a place in the merchant guilds and buy a share in a first ship",
       life="a fleet of one's own"),
  dict(name="a name sung in every tavern", means="B1", domain="pursuit", stages="child juvenile young_adult",
       worlds="magic", passion="being sung about", plan="do something so bold that the bards make a song of it",
       life="a song about oneself in every tavern of the realm"),
  dict(name="a travelling bard", means="R1", domain="career", stages="juvenile young_adult", worlds="magic",
       passion="music and the open road", plan="learn the lute and take to the roads",
       life="a ballad of one's own that the whole realm sings"),
  dict(name="an adventurer", means="R1", domain="pursuit", stages="child juvenile young_adult", worlds="magic",
       passion="adventure", plan="join a company setting out beyond the mountains",
       life="a life of stories no one else can tell"),
  dict(name="a keeper of the old grove", means="G1", domain="faith", stages="child juvenile young_adult mature elder",
       worlds="magic", passion="the old powers of the grove",
       plan="serve the grove's druid and learn its rites (its deeper magic needs a gift to awaken)",
       life="to keep the grove as the druids have kept it for a thousand years"),
  dict(name="to carry on the family holding", means="G1", domain="career", stages="child juvenile", worlds="magic",
       passion="the holding", plan="work beside the family until the holding passes on",
       life="a holding handed on, in good heart, to one's own children"),
  # two colors
  dict(name="a ward-mage who guards the walls", means="W.5 U.5", domain="career", stages="juvenile young_adult",
       worlds="magic", passion="wards and spells of protection",
       plan="train with the wardens' mages (needs a gift to awaken)", life="a city no curse can enter"),
  dict(name="a spymaster of the court", means="U.5 B.5", domain="career", stages="juvenile young_adult adult",
       worlds="magic", passion="secrets", plan="find a place at court and learn whom to listen to",
       life="to know every secret in the realm"),
  dict(name="to learn the secrets the old gods keep", means="U.5 B.5", domain="faith",
       stages="young_adult adult mature elder", worlds="magic", passion="the hidden lore of the gods",
       plan="earn the key to the temple's sealed books", life="to know what the Orders keep hidden"),
  dict(name="a champion of the tournament", means="B.5 R.5", domain="pursuit", stages="child juvenile",
       worlds="magic", passion="the joust", plan="ride in the tournament and win a first prize",
       life="the champion's crown at the great tournament"),
  dict(name="a sellsword who answers to no one", means="B.5 R.5", domain="career",
       stages="juvenile young_adult adult", worlds="magic", passion="the free companies",
       plan="join a free company and win a name in it", life="a company of one's own"),
  dict(name="a ranger of the borderlands", means="R.5 G.5", domain="career", stages="child juvenile young_adult",
       worlds="magic", passion="the wild borderlands", plan="join the rangers on the border",
       life="to know every trail of the wild lands"),
  dict(name="a seat on the city council", means="W.5 B.5", domain="community", stages="juvenile young_adult adult mature elder",
       worlds="magic", passion="the city's affairs", plan="win a seat on the council", life="to be lord mayor"),
  dict(name="a master of one's guild", means="W.5 B.5", domain="career", stages="juvenile young_adult adult",
       worlds="magic", passion="the guild",
       plan="finish the apprenticeship and make a masterpiece the guild accepts", life="to be guildmaster"),
  dict(name="an alchemist's venture of one's own", means="U.5 R.5", domain="career",
       stages="juvenile young_adult adult mature", worlds="magic", passion="alchemy",
       plan="set up a workshop and sell a first new brew", life="a discovery that changes alchemy for ever"),
  dict(name="to build a flying ship", means="U.5 R.5", domain="pursuit", stages="child juvenile adult",
       worlds="magic", passion="flying machines", plan="build a flying ship and get it off the ground",
       life="to sail the sky in a ship of one's own design"),
  dict(name="a hedge-witch", means="B.5 G.5", domain="career", stages="juvenile young_adult adult", worlds="magic",
       passion="herb-craft and the small magics",
       plan="learn herb-craft from a hedge-witch (the small magics need a gift to awaken)",
       life="a cottage at the edge of the woods, and a fee for every cure"),
  dict(name="a paladin", means="W.5 R.5", domain="faith", stages="child juvenile young_adult", worlds="magic",
       passion="the holy fight", plan="take the vows of a holy order and ride out",
       life="to be the shield of the faithful"),
  dict(name="to slay a dragon", means="W.5 R.5", domain="pursuit", stages="child juvenile", worlds="magic",
       passion="facing down monsters", plan="train with the sword until one is ready to face a dragon",
       life="a dragon slain, and the town it threatened safe"),
  dict(name="to raise a griffin", means="U.5 G.5", domain="pursuit", stages="child juvenile young_adult",
       worlds="magic", passion="magical beasts", plan="find a griffin's egg and raise the chick by hand",
       life="to fly on a griffin of one's own raising"),
  dict(name="to find every rare herb in the deep woods", means="U.5 G.5", domain="pursuit",
       stages="child adult mature elder", worlds="magic", passion="herb-hunting",
       plan="map the deep woods and the herbs of each season", life="a herbal with every plant of the realm in it"),
  # three colors
  dict(name="a lasting peace between the town and the forest folk", means="W.4 U.3 G.3", domain="community",
       stages="juvenile young_adult adult mature elder", worlds="magic", passion="making peace",
       plan="learn the forest folk's tongue and broker a first treaty",
       life="a peace that outlasts both peoples' grudges"),
  dict(name="a court mage", means="U.4 W.3 B.3", domain="career", stages="child juvenile young_adult",
       worlds="magic", passion="the arts of the court",
       plan="rise through the academy to a post at court (needs a gift to awaken)", life="the Archmage's chair"),
  dict(name="a tower of one's own, answering to no Order", means="B.4 U.3 R.3", domain="pursuit",
       stages="juvenile young_adult adult mature elder", worlds="magic", passion="power of one's own",
       plan="master the arts the Orders keep from their pupils (needs a gift to awaken)",
       life="a tower of one's own, and no master but oneself"),
  dict(name="a monster hunter", means="R.4 B.3 G.3", domain="career", stages="child juvenile young_adult",
       worlds="magic", passion="hunting monsters", plan="hire out against the beasts of the deep woods",
       life="a hall hung with trophies of the deadliest beasts"),
  dict(name="an inn at the crossroads", means="G.4 W.3 R.3", domain="career", stages="young_adult adult mature elder",
       worlds="magic", passion="keeping an inn", plan="work at an inn and save for one of one's own",
       life="the inn every traveller hopes to reach by nightfall"),
  dict(name="to win back the family's lost lands", means="B.4 W.3 G.3", domain="pursuit",
       stages="young_adult adult mature elder", worlds="magic", passion="the family's lost lands",
       plan="petition the court and save to buy back the first field", life="the family's lands and title restored"),
  dict(name="a duellist of the academy", means="R.4 U.3 W.3", domain="pursuit", stages="child juvenile young_adult",
       worlds="magic", passion="duelling",
       plan="train in the duelling yard (the duelling spells need a gift to awaken)", life="never to lose a duel"),
  dict(name="a potion-maker whose brews sell across the realm", means="G.4 U.3 B.3", domain="career",
       stages="juvenile young_adult", worlds="magic", passion="potion-craft",
       plan="learn the herb-lore and brew a potion people pay for", life="a potion house known across the realm"),
  dict(name="a general of the realm", means="W.4 B.3 R.3", domain="career", stages="child juvenile young_adult",
       worlds="magic", passion="the art of war", plan="earn a command in the realm's army",
       life="to lead the realm's armies"),
  dict(name="to find the lost city of the elder folk", means="U.4 R.3 G.3", domain="pursuit",
       stages="child juvenile young_adult elder", worlds="magic", passion="lost places",
       plan="learn the old maps and set out into the deep forest", life="to walk the streets of the lost city"),
]
