# Chroma Library: the spheres of society, the words the game reads (item 15, phase 1). Library thread, 2026-10-09.
# Plain data, modern days. Keys are sphere and colour ("gather.R") or the subsector ("gather.house"), never a name,
# so a rename never breaks a key (chroma-ideas/spheres-implementation.md section 4). Drawn from
# chroma-ideas/spheres-data/<sphere>.json and checked by chroma-library/tests/check_spheres.py.
#
# SPHERE        each sphere's name and the question it answers in a life
# FACE          the 45 faces: name (a motive, never a place), the line, and the hover line for each driver that moves it
# PLACE         the 60 kinds of place: the modern name and five readings, one per face (role and reading)
# RUNG          the five rungs of standing per sphere, in LADDER order (newcomer, regular, known, pillar, leader)
# PLACE_SHORT   the seven epoch place names over five words, shortened (the epoch words wait for item 17)
# No line names a color.

SPHERE = {
    'rule': dict(name='Rule and law', question='Whose say counts, mine included, and will I get a fair hearing when I am wronged?'),
    'gather': dict(name='Gathering', question='When the work is done, where do I go, who knows my name there, and what do we become together?'),
    'arts': dict(name='Arts and lore', question='Whose songs and stories made me, which are mine, and what will I add that others will sing or tell after me?'),
    'faith': dict(name='Faith and rites', question='What is my life for, who stands with me at its turning points, and what do I owe to what is beyond me?'),
    'care': dict(name='Care and healing', question='When a body fails, mine or someone I love, who carries whom, at what cost, and what do we owe each other?'),
    'learn': dict(name='Learning', question='What will I come to know and be able to do, who will teach me, and which doors will my learning open or close?'),
    'prod': dict(name='Production', question='What will my hands and days make, with whom and on whose terms, and will it feed us and mean something?'),
    'comm': dict(name='Commerce', question='What is a fair exchange, whom can I trust with what I have, and will my trade and debts free my life or bind it?'),
    'prot': dict(name='Protection', question='Who keeps me and mine safe, at what price, and will I ever be asked to stand guard, or to fight?'),
}

FACE = {
    "rule.W": dict(name='A fair hearing',
        line='The magistrate reads both claims aloud, slowly, so the man who cannot read hears exactly what he is agreeing to.',
        hover={'insecurity': 'After feuds, riots or a lawless spell, people want a hearing more than revenge.', 'plenty': "Good years fill the purse that pays judges, clerks and jurors' lost days.", 'crowding': 'Many strangers must live and trade together, and need one rule for all.', 'schooling': 'More people can read the law and hold every hearing to it.', 'exposure': 'A scandal comes to light and people turn to a fair hearing to set it right.', 'change': 'New tools, routes and ways of living outrun the rules, which no longer fit.'}),
    "rule.U": dict(name='Reasoned law',
        line='The clerk finds the same field promised to two families forty winters apart, and spends a season working out which promise came first.',
        hover={'insecurity': 'After thefts, riots and feuds, people want the facts found, the record kept and rules that actually work.', 'war': 'War needs musters, supply rolls and counted levies.', 'crowding': 'A growing town needs records, plans and clear rules for strangers.', 'inequality': 'A few grow rich enough to buy the rules, and favour beats evidence.', 'exposure': 'A scandal opens the books, and audits and inquiries follow.', 'change': 'New tools and routes arrive and need new rules drafted.'}),
    "rule.B": dict(name='Favour and following',
        line='The new councillor wanted one thing: the bridge her ward was promised twenty years ago. She traded three votes she cared nothing for, and it stands.',
        hover={'insecurity': "Disorder breaks bargains, and people want one firm rule over a patron's word.", 'plenty': 'A boom makes new fortunes that want a say and can pay for a following.', 'war': 'War puts the rule under one command, and there is no room left to bargain for favours.', 'inequality': 'The gap widens, and people need a patron to be heard at all.', 'schooling': 'People who can read the law themselves need no broker.', 'exposure': 'Audits and free news bring favours to light.'}),
    "rule.R": dict(name='Raised voices',
        line='Everyone at the meeting thinks the toll is wrong. One woman stands up and says so, and suddenly everyone does.',
        hover={'insecurity': 'Fear and disorder make people want calm before voice.', 'plenty': 'Good years and steady pay quiet the call; hard times bring it back.', 'inequality': 'The gap widens, and those left behind get no hearing.', 'schooling': 'More people can read the law and the news, and answer back.', 'exposure': 'A wrong comes to light and people will not wait for an inquiry.', 'change': 'New ideas and new ways to speak out arrive from elsewhere.'}),
    "rule.G": dict(name='Old custom',
        line='The young mediator does not judge. She has the two families eat at one table until the quarrel is smaller than the meal.',
        hover={'insecurity': 'Disorder breaks the ties that let go-betweens settle things.', 'plenty': 'Boom years let people buy their way out of custom; hard times bring them back to kin.', 'crowding': 'Newcomers who share no custom crowd in, and the town outgrows knowing everyone.', 'inequality': 'The gap widens, and the big holders stop keeping the shared customs.', 'schooling': 'Written law that many can read replaces remembered custom.', 'exposure': 'News and scandal show the keepers of custom shielding their own kin.', 'change': 'New tools and ideas make the old ways fit life less.'}),
    "gather.W": dict(name='No one left out',
        line='Every week someone sets out the chairs, and every week the old widow has her seat by the stove.',
        hover={'insecurity': 'Fear on the streets sends people to a known door, a set night and someone to walk them home.', 'plenty': 'Hard times make a whip-round or a shared supper matter; in boom years some trade the set night for paid nights out.', 'war': 'War years most of all: the community feeds the families of the absent, sends parcels and mourns together.', 'crowding': 'A swelling town of strangers outgrows the room where everyone knew everyone.', 'change': 'New pastimes and new working hours pull the young away from the set night.'}),
    "gather.U": dict(name='Good talk',
        line='On the first night of each month they choose one question and argue it until the candles are stubs.',
        hover={'insecurity': 'Informers and fear: people stop saying what they think in company.', 'plenty': 'Lean years above all: with no coin for a night out, people crowd the reading room to work out what went wrong.', 'war': 'War quiets the arguing tables most of all: censors read the post, talkers are called up, and chairs stay empty.', 'crowding': 'A fast-swelling town: rents price out the quiet rooms, and the din drowns the table.', 'inequality': 'Rich and poor stop sharing a table, so the argument loses half its voices.', 'exposure': 'News breaks or a scandal comes to light, and everyone wants to weigh what it really means.'}),
    "gather.B": dict(name='Useful company',
        line='They saved two years for the fee, and the first person they put up for membership was the cousin no one else would sponsor.',
        hover={'insecurity': 'Unsafe streets: people pay for a door that knows who comes in, and a host who can vouch for them.', 'war': "War years: call-ups and rationing thin the members' tables, and shared duty counts for more than favours.", 'inequality': 'A widening gap: the right table is worth more, and people climb by whom they know.'}),
    "gather.R": dict(name='High spirits',
        line='Someone starts a song nobody knows the end of, and by midnight the whole room is making one up.',
        hover={'insecurity': 'Fear on the streets after dark: people go home early and the night empties.', 'plenty': 'Good years bring more nights out on the dance floor; in lean years the rounds are counted and people go home early.', 'inequality': 'A widening gap splits the night: dear places shut the many out and cheap ones turn rough.', 'schooling': 'Longer schooling gathers the young into a crowd of their own, with their own nights and music.', 'exposure': 'A death or a scandal at a venue brings the licence men and the moralists down on every night out.', 'change': 'A new music, a new dance or a new drink arrives, and everyone goes out to try it.'}),
    "gather.G": dict(name='Familiar faces',
        line='Every autumn the same long table, the same dish, and one more chair for the newest baby.',
        hover={'plenty': 'Good harvests fill the long table and the feast round most of all; hard times cut the feast first.', 'war': "War draws kin and neighbours close: shared rations, the street's own feast, the names of the dead kept.", 'crowding': 'Newcomers arrive and keep home ways in the new town: their own tables, dishes and feast days.', 'schooling': 'Longer schooling takes the young to new towns and new company, and the family table waits for the holidays.', 'change': "New routes and pastimes break the year's round: the feast moves, then lapses."}),
    "arts.W": dict(name='Art that binds',
        line='At the funeral the whole street sang the old song together, and for the first time since the news came, they did not feel alone.',
        hover={'insecurity': 'Fear and disorder send people to the vigil and the shared song that steady a frightened town.', 'plenty': 'In good years people buy their own nights out and the shared rite feels dull; hard years bring it back.', 'crowding': "A fast-growing town's newcomers and old residents share no rite yet; a town people leave keeps its rites closer.", 'inequality': 'The rich hold their ceremonies apart, and the common one rings false.', 'schooling': 'Readers pick their own books and songs over the repertoire everyone once shared.', 'exposure': "Scandal shows the rite's sponsors using it, and the anthem is sung with a smirk.", 'change': 'New forms and tools make the set forms feel dated to the young.'}),
    "arts.U": dict(name='True form',
        line='They played the same four bars every night for a month, until the night the hall went silent and they understood why.',
        hover={'insecurity': 'Fear and disorder close the practice rooms; no one can spend years on a craft.', 'war': 'Pupils are called up, and patient work waits for peace.', 'inequality': 'Rich patrons and keen connoisseurs pay for long training and difficult, refined work.', 'schooling': 'A vast new reading public wants the quick serial and the hit, and slow, exacting work loses its share.', 'change': 'New tools and forms, from a new scale to the recording desk, invite study and trial.'}),
    "arts.B": dict(name='Making a name',
        line="They refused the patron's third offer, named their own price, and opened under their own name, with every friend who had backed them in the front row.",
        hover={'insecurity': 'Unsafe roads stop the tours, debts go unpaid and the paid seats empty.', 'plenty': "Booms and new money fill the paid seats and the patrons' purses.", 'war': 'War songs sell, and singers who tour the camps and play to soldiers on leave make their names.', 'crowding': 'A growing town brings new paying crowds and more stages to book.', 'exposure': 'News, gossip and scandal make names: with every eye on the stage, even a bad notice sells seats.'}),
    "arts.R": dict(name='Raw feeling',
        line='No one had written the song down; they made it up that night on a borrowed drum, and the whole room sang the chorus back.',
        hover={'insecurity': "Weak rule leaves the cellar beyond the censor's reach, and grief and anger need a voice.", 'war': 'Players are called up, curfews fall and the anthem drowns out the mocking song.', 'crowding': 'A crowded, growing town of newcomers, mixed streets and cheap rooms is where scenes start.', 'schooling': 'More people can write their own verses, songs and satires and pass them hand to hand.'}),
    "arts.G": dict(name='Living tradition',
        line='Their grandmother taught them the wedding song line by line; at the next wedding they sang it, and the old ones cried.',
        hover={'war': 'Threat from outside makes a people hold to its songs and dances to know who it is.', 'crowding': 'In a fast-growing town the keepers are outnumbered and the young learn their songs from everywhere.', 'schooling': 'Readers write down the old songs and tales, and the school teaches them in the home tongue.', 'exposure': 'The outside eye turns a living rite into a show for visitors, and the young stop learning it for its own sake.'}),
    "faith.W": dict(name='Mercy and duty',
        line='Every week she takes the list of the sick and visits each name, even the old man who has never once thanked her.',
        hover={'insecurity': 'Fear and disorder: the faithful close ranks, keep watch for each other and carry the weak.', 'plenty': 'Long plenty: few need the alms door, and shared duty thins into habit.', 'war': "War: the vigils, the widows' fund and the rolls of the dead fall to the faithful.", 'crowding': 'A crowded, fast-growing town: no one knows whom to visit, and the rota breaks.', 'inequality': 'A widening gap: the alms door and the visiting list feed those left behind.', 'schooling': 'Wide schooling: people weigh duty for themselves, and a rule asked of all feels imposed.', 'exposure': 'A hypocrisy brought to light: the keepers did not keep the rule they asked of others.', 'change': 'New tools and ways arriving: the fixed rites seem to belong to another time.'}),
    "faith.U": dict(name='Seeking truth',
        line='She mops the temple floor at dawn, then sits an hour with the old book, arguing with it in the margins.',
        hover={'insecurity': 'Fear and disorder: people want comfort and a firm word, not a question.', 'plenty': 'Plenty: there is time to read, to sit still and to argue the teaching through.', 'war': 'War: houses of study empty, the young are called away, books burn.', 'inequality': "A widening gap: the poor have no hour to study, and the teaching becomes a few people's.", 'schooling': 'Schooling spreads: more people read the teaching for themselves and ask what it means.', 'exposure': 'Things brought to light: old texts found, scandals argued, teachings compared in the open.'}),
    "faith.B": dict(name='Chosen path',
        line='She made her vow at the shrine: if the shop lived through the winter, she would pay for the new roof. It did. She paid.',
        hover={'insecurity': 'Fear and disorder: a private bargain feels thin, and people crowd into the shared rite.', 'war': "War and danger: vows for a safe return, a soldier's own prayers, a bargain struck for one life.", 'inequality': 'A widening gap: few can pay for vows and offerings, and the ranks close to outsiders.', 'schooling': 'Schooling spreads: readers choose a faith for themselves, switch when it fails them, and rise through its schools.', 'change': "New routes and ideas: more faiths to choose from, and room to found one's own."}),
    "faith.R": dict(name='Living fire',
        line='No one planned for the singing to go on past midnight. No one wanted it to stop, and three people walked home changed.',
        hover={'insecurity': 'Fear and disorder: people need the sacred felt now, and revivals spread fast.', 'plenty': 'Boom years and comfort: the urgency fades and the singing grows polite.', 'war': 'War: vigils, oaths and songs carry the grieving and the called-up.', 'crowding': 'Newcomers fill a growing town: the uprooted find each other in song.', 'inequality': 'A widening gap: the poor and passed-over find a voice where the spirit, not rank, decides.', 'schooling': 'Wide schooling: the measured rite wins the schooled, and the trance is mocked as unlearned.'}),
    "faith.G": dict(name='Ancestors and seasons',
        line='Each spring the family sweeps its graves, and this year the youngest daughter tells the children who lies where.',
        hover={'insecurity': "Fear and disorder: feasts are cancelled, graves go unswept, the year's round breaks.", 'plenty': 'Good harvests and plenty: the feasts, the funerals and the gifts to the dead can all be afforded.', 'war': 'War: the young gone, the dead buried far away, the round broken for years.', 'crowding': 'Newcomers keep their home rites in a new town, and each quarter keeps its own festivals.', 'schooling': 'Wide schooling: the household rites are taught as superstition, and the young stop learning them.', 'exposure': 'A scandal at the great houses of faith sends people back to the household rite and the family graves.'}),
    "care.W": dict(name='Care for all',
        line='The night nurse writes every change in the book before dawn, so whoever comes next finds nothing half-explained.',
        hover={'plenty': 'Good years fill the common purse that pays for beds, nurses and the night round.', 'war': 'War takes the beds, the nurses and the purse for the host.', 'crowding': 'A town fills with newcomers and strangers whom no kin will nurse, and a bed by need is the only way.', 'inequality': 'The gap widens and the well-off buy their way out of the common ward, taking its funds with them.', 'exposure': 'Neglect inside a house of care comes to light, and trust in the fair rule falls with it.', 'change': 'New ways of care arrive and are made into one standard for every bed.'}),
    "care.U": dict(name='Proven cure',
        line="No one could name his wife's illness, so he logged every meal and every bad night, and found the pattern the healer missed.",
        hover={'insecurity': 'Disorder burns the records and scatters teachers and pupils.', 'plenty': 'Good years pay for study, instruments and the long apprenticeship of the hand.', 'war': 'War fills the field tents, and surgeons learn in a season what peace takes decades to teach.', 'inequality': 'The rich buy famous names and the poor go to kin, so the tested way loses its patients.', 'schooling': 'More people read, so remedies and records travel and patients follow the regimen.', 'exposure': 'A learned cure fails or harms in public, and trust in experts falls.', 'change': 'New instruments and contact abroad bring cures to test.'}),
    "care.B": dict(name='Chosen healer',
        line='When the healer gave her father a month, she refused the verdict, spent her savings on a second opinion, and he lived to dance at her wedding.',
        hover={'insecurity': 'Fear and disorder close the roads to the healer one would choose, and the sick take whatever help is nearest.', 'war': 'War puts care under one command, and private rooms are taken for the wounded.', 'inequality': 'The gap widens, and those who can pay buy the healer they want and a room of their own.', 'schooling': "Schooling spreads and trained healers multiply, so a name of one's own counts for less."}),
    "care.R": dict(name='Rush to help',
        line='At seventy he still drives the night ambulance, because someone has to be the one who comes.',
        hover={'insecurity': 'Fear, disorder and disaster, when help must come before any rule can.', 'plenty': 'Long easy years, when care settles into appointments and routine.', 'war': 'War and raids, when the wounded must be carried now.', 'crowding': 'A growing town brings a house of care within reach, and help comes by rota.', 'schooling': 'Training and licences become the rule, and unlicensed help is turned away.', 'exposure': 'A rescue is seen and told, and others step forward to be the one who comes.', 'change': 'New tools and set procedures replace the bold improvised fix.'}),
    "care.G": dict(name='Kin who carry',
        line="The midwife who caught half the street's children now sits with their grandmothers at the end, and needs to fix nothing.",
        hover={'insecurity': 'Fear and disorder keep the sick at home, among kin who can be trusted.', 'plenty': 'Boom years draw kin into paid work, and the hours for nursing go.', 'war': 'War takes the young away and leaves too few hands at home.', 'crowding': 'Newcomers crowd in far from their own kin, with no one near to carry them.', 'inequality': 'Care is priced beyond reach, and families nurse their own.', 'schooling': "More can read, and household remedy books and carers' guides make home nursing surer.", 'exposure': 'Neglect in the big houses of care comes to light, and families take their old back home.', 'change': 'New tools and cures arrive, and the old home remedies lose their place.'}),
    "learn.W": dict(name='Every child taught',
        line='By spring every child in the room could read the notice on the mill door. The teacher counted it the best year of her life.',
        hover={'insecurity': 'Fear and disorder shut the school doors and keep children at home.', 'plenty': 'A good surplus pays the teachers and lets families spare their children from work.', 'war': "War takes the teachers, the school's purse and the older pupils.", 'crowding': 'Newcomers crowd in, and their children must be taught together, in one tongue.', 'inequality': 'The gap between rich and poor moves reformers and the faithful to open free schools.', 'schooling': 'Parents who can read want the same for every child, and schools for all win wide support.', 'exposure': 'A report of untaught or neglected children shames the town into acting.', 'change': 'New trades need lettered, reliable hands, and the school is asked to supply them.'}),
    "learn.U": dict(name='Pure inquiry',
        line='He checked the sums a fourth time, found the mistake that had stood for thirty years, and ran to tell the pupil whose question had started it.',
        hover={'plenty': 'A surplus pays for years of study that need not earn their keep.', 'inequality': 'Wealthy patrons with time and money to spare keep scholars and their long questions.', 'schooling': 'The purse goes to teaching the many, and long questions with no use go unpaid.', 'exposure': "A faked result or a scholar's scandal comes to light, and people stop trusting the learned.", 'change': 'New tools and routes pull the learned toward what can be built and sold now.'}),
    "learn.B": dict(name='Getting ahead',
        line="Her mother cleaned the examiners' rooms. She passed fourth of four hundred, and never once let them see her nervous.",
        hover={'insecurity': 'Uncertain times make a portable skill or a credential the one thing no one can take.', 'plenty': 'A boom hires anyone who turns up, so few study for an edge; hard times make every place worth a fight.', 'war': 'War calls the young from their books and turns posts into luck.', 'inequality': 'Posts go by birth and wealth, and no amount of study opens the door.', 'schooling': 'Everyone holds the same certificate, and it no longer sets anyone apart.', 'exposure': 'A scandal of bought places or leaked papers breaks, and every quick rise is doubted.'}),
    "learn.R": dict(name='Learn by doing',
        line='At sixty he bought a broken engine for fun. He took it apart on the kitchen floor three times; the fourth time it ran.',
        hover={'war': 'War needs hands that learn on the job, and veterans come home with a trade in their hands.', 'crowding': 'A crowding town fills every bench, and the young are sent to rooms and waiting lists.', 'inequality': 'The few own the tools and benches, and the young cannot get their hands on them.', 'schooling': 'Long schooling takes the hours that once went to trying things at the bench.'}),
    "learn.G": dict(name='Handed-down knowing',
        line='Her father never wrote anything down. Walking the hedges with him, she learned every plant she would ever need.',
        hover={'insecurity': 'In fearful times people turn to what their own people know works.', 'plenty': 'A boom draws the young to bought goods and new wages, and the old skills go unused.', 'war': 'War cuts the roads and the bought goods, and the old skills of making do come back.', 'crowding': 'A crowding town of strangers breaks the chain from one generation to the next.', 'schooling': 'Readers write the old knowing down, and schools teach the home tongue and lore.', 'exposure': 'News that a tongue or craft is nearly lost, or that children were shamed for it, brings the young back.'}),
    "prod.W": dict(name='Honest work',
        line="Thirty years a master, and he still sends back his own work when it falls short. 'Someone will trust this,' he says.",
        hover={'plenty': 'A boom lets any hand name a price across the road, so the shared rule and the fair share feel needless.', 'war': "War suspends the trade's rules: strikes banned, safety waived, every hour given to the war's orders.", 'crowding': 'Newcomers arrive faster than the rolls can take them, and work grows up outside the rules.', 'inequality': 'When a few own the land and the works, the hands band together for fair shares and a kept rule.', 'schooling': "Schools certify skill, so the trade's own training and its mark lose their hold.", 'exposure': 'An accident or bad goods come to light, and people call for standards and safety rules.', 'change': 'New machines bring new dangers, and the trade writes the rules that make them safe.'}),
    "prod.U": dict(name='Better methods',
        line='Every evening she writes down the catch, the wind and the water. After twelve years the old skippers start asking to see her notebook.',
        hover={'war': 'War demands more from fewer hands: standard parts, measured rations, faster lines.', 'crowding': 'Newcomers make hands cheap and plentiful, so saving labour no longer pays.', 'inequality': 'Big estates and large works can afford trials and pay improvers to run them.', 'exposure': 'A celebrated method is exposed as failing or harmful, and trust in improvers collapses.'}),
    "prod.B": dict(name='Own account',
        line='He bought his first loom on a loan nobody else would give, worked it nights after his shift, and by forty he employed the street.',
        hover={'insecurity': 'Theft, raids and broken contracts mean no one builds what can be seized.', 'plenty': 'Credit is easy and demand rising, so a loan for a boat, a loom or a firm pays back.', 'war': 'War orders need makers and contractors who can deliver fast.', 'crowding': 'A growing town brings buyers to sell to and hands to hire.', 'inequality': 'A few great holders own the land and the works, and a small owner cannot get a start.', 'schooling': 'Schooled people can keep accounts, read contracts and start firms of their own.', 'exposure': 'Prices and markets come into the open, so small makers find buyers without a middleman.'}),
    "prod.R": dict(name='Free hand',
        line='She walked out of the workshop the day the master struck her friend, and has sold only the pots she loves at the fair ever since.',
        hover={'insecurity': 'Roads and markets turn unsafe, so the free hand cannot range for work or buyers.', 'plenty': 'Plenty leaves room to risk a living on what one loves, and to walk out and find other work.', 'war': 'War calls up the free hands and directs every trade to its orders.', 'inequality': "A few own every boat and workshop, and the rest must take the wage on the master's terms.", 'schooling': 'Every trade asks for a certificate, and those who learned by hand are shut out.', 'change': 'New machines and the clock take over the made thing, and the craft by hand becomes a line.'}),
    "prod.G": dict(name='For those who come after',
        line="At twenty-two the baker's granddaughter took over the oven, kept the old starter alive, and changed one thing: she opens at dawn for the night shift.",
        hover={'insecurity': 'Raids, theft and weak rule make people put their work into what cannot be seized: a skill taught, a crew of kin, stores put by.', 'plenty': 'A boom draws the young to quick wages and lifts prices until holdings and family firms are sold.', 'war': 'War takes the young who would carry the work on, and the horses, the herds and the stores.', 'crowding': "A growing town needs the farm's food and the workshop's goods, and newcomers ask to be taught the trade.", 'inequality': "Big holders buy out the small, and debt forces the family's sale.", 'schooling': 'Schooled young people come home with records, new skills and reasons to carry the work on.', 'change': 'A new tool or route lets a small holding, crew or workshop make a living worth handing on.'}),
    "comm.W": dict(name='Fair measure',
        line='Her scales were checked every spring and never once found light. Half the street bought from her for that alone.',
        hover={'insecurity': 'Disorder and weak rule leave no one to check a weight or enforce a promise.', 'plenty': "A boom makes checks and caps feel like a brake on everyone's gains.", 'war': 'War brings shortages, and people want rations and prices set the same for all.', 'crowding': 'Newcomers crowd in faster than the rolls and wardens can follow, and trade spills past the rules.', 'schooling': 'Most people can read a price board, a receipt or a contract for themselves.', 'exposure': 'A false weight, a fraud or a famine price is brought to light.', 'change': 'New coin, new goods or new ways to pay need standards everyone can check.'}),
    "comm.U": dict(name='Careful reckoning',
        line='He kept the household book in a small hand for forty years. When the bad winter came, he already knew how long they could last.',
        hover={'insecurity': 'Roads are unsafe and courts weak, so insurance, spread risk and paper in place of coin pay off.', 'plenty': 'A boom rewards guessing and makes the careful look timid.', 'war': 'War sets prices by decree and seizes cargoes, and no forecast holds.', 'crowding': 'The town fills faster than any record can follow, and trade runs on cash in hand.', 'schooling': 'More people learn to read, count and keep accounts.', 'exposure': 'Prices and accounts are published, so careful comparison pays.', 'change': "New routes, goods or ways to pay make last year's figures wrong."}),
    "comm.B": dict(name='Shrewd bargain',
        line='She started with one cart of oranges and a secret loan. At fifty, three streets bought from her, and she still checked every crate.',
        hover={'insecurity': "Courts are weak, and a deal holds only by one's own word, wits and name.", 'crowding': 'Crowds of new sellers undercut every margin.', 'inequality': 'A few great houses hold the licences, the credit and the best pitches, and no newcomer can get a stake.', 'schooling': 'Buyers can read, compare and check, so the edge of knowing more is gone.', 'exposure': "A hard bargain's terms come to light, and caps, boycotts and lawsuits follow.", 'change': 'New routes, goods or ways to pay open gains for whoever takes a stake first.'}),
    "comm.R": dict(name='Haggle and dare',
        line='He sold rugs for thirty years and never sold two at the same price. He said the day he did, he would retire.',
        hover={'insecurity': 'Robbers on the roads and thieves in the market make the pack and the open stall unsafe.', 'plenty': 'Good years leave people money to spend, and a pitch is cheap to start.', 'war': 'War closes the roads, the fairs and the borders.', 'crowding': 'Fairs, ports and growing towns bring crowds to sell to, though more sellers come with them.', 'schooling': 'Trade moves to written terms, price tags and forms, and the haggle gives way to the fixed price.', 'exposure': 'A con comes to light and the whole street of hawkers is blamed.', 'change': 'New ways to buy, from catalogues to screens, draw custom off the street.'}),
    "comm.G": dict(name='Gift and return',
        line='Nobody in the lane paid her for the eggs. Every winter, without being asked, someone fixed her roof.',
        hover={'insecurity': 'Fear and theft make each household guard its own store, and gifts shrink to the nearest kin.', 'war': 'War and rationing make neighbours swap, share and carry each other.', 'crowding': 'Newcomers pour into a growing town and lean on kin and home-town ties for credit, a bed and a first job.', 'inequality': 'Banks and lenders shut out the poor, so neighbours lend to each other.', 'schooling': 'The young can write home, and gifts and money flow along kin ties to far places.', 'exposure': "News of cheaper prices elsewhere makes the neighbour's price look like a favour no one can afford.", 'change': 'New ways to send money let kin help kin from far away.'}),
    "prot.W": dict(name='Equal protection',
        line='Thirty years on the night watch, and he still walked the alley behind the tannery, where no one important ever lived.',
        hover={'insecurity': 'Fear and disorder outrun the watch, and people stop waiting for the common peace.', 'plenty': 'Good years fill the common purse: the watch is paid on time, and more streets are lit and walked.', 'crowding': 'A town fills with strangers who share no kin, and needs one watch for all of them.', 'inequality': 'The gap widens: the rich buy their own guards, and the common watch is left thin on the poor streets.', 'schooling': 'More people are schooled: officers who know the law they keep, and people who know their rights.', 'exposure': 'An abuse or a bribe in the watch comes to light, and trust in one peace for all drains away.'}),
    "prot.U": dict(name='Early warning',
        line='She noticed the stolen goods always reached the market on rain days. By autumn the thieves were caught, and no one was hurt.',
        hover={'plenty': 'Long good years make warnings look like a needless cost; hard years make the cheap warning worth more than the costly fight.', 'war': 'War rewards knowing the enemy: scouts, ciphers, maps and planned supply.', 'crowding': 'A crowded town needs inspections, fire rules, and someone to see the pattern in the thefts.', 'inequality': 'As the gap widens, those with most to lose pay for alarms, risk reports and quiet inquiries.', 'exposure': 'Secret files come to light, and people turn against being watched.', 'change': 'New tools let the watchers see further: the signal tower, the telegraph, the camera.'}),
    "prot.B": dict(name='Skill at a price',
        line='He guarded the salt caravans for twenty years, never cheaply, and never lost a load. Merchants called his fee the best bargain on the road.',
        hover={'insecurity': 'Fear rises faster than the watch can answer, and those who can pay hire their own guards.', 'plenty': 'A boom pays the common watch well and draws skilled hands into easier work; hard times send them back to selling their skill.', 'war': 'A great war calls up every able body and folds the companies into the host; when it ends, trained fighters look for paid work.', 'crowding': 'A growing town of warehouses, shops and late nights hires door staff and night guards, and its force has ranks to climb.'}),
    "prot.R": dict(name='Courage first',
        line='Thieves came for the mill. At sixty-two he did not wait for the watch; he took a lantern and a stick and went out shouting.',
        hover={'insecurity': 'Fear and disorder spread: doors are locked, evenings kept in, and few run toward trouble.', 'plenty': 'Good years leave time and strength to spare for the volunteer company and the drill; hard years keep everyone at work.', 'crowding': 'A growing town pays professional crews, and the volunteers and street champions are stood down.', 'inequality': 'As the gap widens, those with little to lose take the risky posts that pay in pride and comrades.', 'exposure': 'A wrong the guard ignored comes to light, and ordinary people resolve to step in themselves.', 'change': "New arms and drill make one person's nerve count for less."}),
    "prot.G": dict(name='Defend our own',
        line='When the river rose, she knocked on every door on the lane before her own, because she knew who could not hear the bell.',
        hover={'insecurity': 'Fear and disorder rise, and neighbours close ranks to watch their own lanes and herds.', 'war': 'A great war takes the able to a distant front, and the home ground is left thin.', 'crowding': "Newcomers arrive faster than neighbours can learn their names, and the lane's watch thins.", 'schooling': 'Schooling sends the able young to posts elsewhere, and trust shifts from kin to trained officers.', 'exposure': 'The official guard is caught in abuse, and people turn to kin and neighbours they can trust.', 'change': "New roads, tools and alarms make the old way of watching one's own ground look slow."}),
}

PLACE = {
    "rule.counsel": dict(name='the council chamber', kind='Counsel',
        W=('the presiding councillor', 'Each member speaks in turn and the rules of order bind the chair too; at the council fire, every grown person may finish.'),
        U=('the clerk who drafts the motion', 'A room for weighing evidence: the motion drafted, the costs counted, the vote taken once the facts are on the table.'),
        B=('the member with a bloc behind them', 'Where a following turns into votes: the deal struck in the corridor brings the ward its bridge.'),
        R=('the member who stands up out of turn', 'Where someone finally says what everyone is thinking, and the public gallery cheers.'),
        G=('the member for the old ward', "The same families' seats for generations; nothing is decided until the old ward can live with it.")),
    "rule.office": dict(name='the agency office', kind='Office and the purse',
        W=('the clerk who treats every file alike', "One queue and one rule: the lord's steward waits behind the widow; early form, the chief's speaker who asks every hearth the same share."),
        U=('the planner who redesigns the form', "A way of knowing the realm: rolls, counts and plans, a little better each year; early form, the scribe's tally of tribute."),
        B=('the official who knows whom to call', 'A ladder and a lever: a post won, a favour done for the ward, a file moved to the top of the pile.'),
        R=('the clerk who bends the rule for the person at the counter', 'A wall to get through: the late form stamped anyway, because the family in front of them cannot wait.'),
        G=('the long-serving clerk who knows every family', 'The same clerk has served the district for thirty years and knows which household needs what before it asks.')),
    "rule.judgment": dict(name='the courthouse', kind='Judgment',
        W=('the judge', 'Both sides heard in full, one law for rich and poor, reasons given aloud; early form, the judges who sit at the city gate.'),
        U=("the keeper of the court's record", 'A place of evidence: old rulings found, facts tested, the precedent set straight for the next case.'),
        B=('the advocate for hire', 'A contest one can win with sharp counsel and the right witness, even against a great house.'),
        R=('the accused who speaks for themselves', 'Where the accused throws away the script and tells the room what really happened.'),
        G=('the lay assessor from the district', "Neighbours who know the families sit beside the judge, and a fair price can mend a quarrel; early form, the elders' hearing.")),
    "rule.law": dict(name='the law archive', kind='Laws and ways',
        W=('the keeper of the statutes', 'The rules kept the same for everyone and open to anyone who asks to read them; early form, the code on the temple wall.'),
        U=('the drafter comparing codes', 'A workshop of rules: compare old codes, find where they failed, draft the next one clearer.'),
        B=('the lawyer looking for an opening', "A map of doors: the clause that frees a client, the charter that grants one's people a right."),
        R=('the campaigner who reads a law aloud to a crowd', 'Proof of the wrong: the law read out so people know exactly what was done to them.'),
        G=('the young keeper who has the customs by heart', "A people's custom kept in words, so the next generation still knows whose field is whose; early form, the tellings at the fire.")),
    "rule.sanction": dict(name='the prison', kind='Sanction and mercy',
        W=('the warden who keeps the rules for inmates too', 'Punishment in proportion, the same for all, and a set day when the debt is paid; early form, the fine in cattle.'),
        U=('the reformer who studies what stops a second offence', 'A place to learn what turns a life around, and to change the regime by what works.'),
        B=('the inmate who speaks for the yard', 'A world with its own order, where those inside build standing and bargain for every comfort the yard gets.'),
        R=('the prisoner of conscience', 'Proof the rule fears a voice: the cell where someone who spoke out keeps on speaking.'),
        G=('the kin who visit and plan the homecoming', 'A break in a family to be mended: visits kept up and a welcome home made ready; early form, exile with a way back.')),
    "rule.voice": dict(name='the polling place', kind='Voice and faction',
        W=('the poll clerk', 'One person, one vote, counted in the open, the same booth for banker and porter; early form, the show of hands at the fire.'),
        U=("the canvasser with the ward's numbers", 'Where a campaign learns, street by street, whether its argument worked.'),
        B=('the organiser who gets the vote out', 'A day of reckoning for a following: every favour done comes back as a vote, and every broken promise costs one.'),
        R=('the first-time voter', 'The one day the quietest person in town can say no out loud.'),
        G=('the family that walks to the poll together', 'A street that has voted the same way for generations, and goes to the poll as one.')),
    "gather.house": dict(name='the bar and the café', kind='Drink and board',
        W=('the keeper who runs the benefit night', "The regulars' benefit night: a whip-round for a widow, last orders kept, someone to see the unsteady home."),
        U=('the quiz master', "The quiz night and the corner table where travellers' news is weighed and the day's argument settled."),
        B=('the keeper who saved for a house of her own', 'The back room where dealers settle terms, and a keeper who saved for years owns the door and the name over it.'),
        R=('the fiddler', 'The loud night: a song started at the bar, a dance between the tables, a story by morning.'),
        G=("the regular who took her father's seat", 'The local where the same families have sat for generations and toast their dead by name; once, the village brew-house.')),
    "gather.hall": dict(name='the community centre', kind='Halls and lodges',
        W=('the treasurer of the benefit fund', "A lodge that visits its sick, pays the widow's rent and keeps every promise written in its book."),
        U=("the society's secretary", 'A society that meets to learn: the chess club, the field walkers, the debating club with its minutes.'),
        B=('the membership secretary', "A members' club one works to be asked into, where sponsors vouch and standing is earned, not inherited."),
        R=('the social secretary who books the band', "The club's dance nights and outings, where the rule book stays shut until Monday."),
        G=('the member whose grandparents joined', "A club that feels like kin, three generations on the roll; early, the age-mates' house where the young grew up together.")),
    "gather.great": dict(name='the park and convention hall', kind='Squares and great gatherings',
        W=('the steward of the common', 'The common kept open to all: one rule for every stall, and a free pitch for the poorest seller.'),
        U=("the convention's programme maker", 'Where notices go up and people stop to read and dispute them; at the convention hall, talks on the newest work.'),
        B=('the stallholder with the best pitch', "A pitch claimed early and made one's own; at the convention, the trade floor where a name and contacts are built."),
        R=('the show-seller of the fair', "The square that fills to celebrate, mourn or protest; the fair's rides, music and wrestling ring."),
        G=('the young father watching the common', "The common where neighbours meet each evening and children play under everyone's eye.")),
    "gather.games": dict(name='the sports ground', kind='Games and sport',
        W=('the referee', 'Fair play: the referee everyone trusts, the rules read out, and every child gets a game.'),
        U=('the coach with the notebook', "The game as a puzzle: tactics drawn in chalk, the scorer who knows every season's figures, the board game by the gate."),
        B=('the promoter of the match', 'The match as a career and a business: gate money, prize purses, the player who signs for a richer side.'),
        R=('the champion wrestler', 'The roar of the crowd and the body in the moment: the race, the bout, the late winner.'),
        G=("the young fan in the family's scarf", 'The home side followed by grandparents and grandchildren alike; early, the wrestling at the summer gathering.')),
    "gather.circle": dict(name='the book group', kind='Circles and salons',
        W=('the chair who gives everyone the floor', 'An evening run fairly: an agenda, a chair, everyone heard once before anyone speaks twice.'),
        U=('the convenor who sets the question', 'A question set, a text read aloud, reasons weighed until the better argument wins; early, the riddling at the fire.'),
        B=('the host whose invitation matters', 'The salon as a ladder: the right guests, the introduction that launches a career, an idea that makes a name.'),
        R=('the poet who reads first', 'The open night where poems, songs and quarrels pour out and nobody waits for the chair.'),
        G=('the teller at the fire', 'The same friends for forty years and the old tellings retold; early, the firelight telling.')),
    "gather.night": dict(name='the night club', kind='Night and dance',
        W=('the door warden who sees everyone home', 'A night kept safe: a warden on the door, water on the bar, a ride home for whoever needs one.'),
        U=('the sound engineer', 'The night as craft: the sound tuned, the set built to a peak, the floor read like an audience.'),
        B=('the promoter', "The night as one's own creation: the promoter's name on the poster, the guest list, the door one decides."),
        R=('the dancer who owns the floor', "The dance floor, the music loud, the self let loose until dawn; early, the young people's own fire."),
        G=('the band that plays every wedding', 'The dance where three generations know the steps and the band has played every wedding for thirty years.')),
    "gather.talk": dict(name='the news feed', kind='News and the word',
        W=('the editor of the notices', 'News as a common good: fair warning, notices of who needs help, a correction printed as large as the error.'),
        U=('the reader who checks the claim', 'News weighed, not swallowed: three accounts compared, the rumour traced to where it began; early, the crier questioned.'),
        B=('the printer with a sheet of their own', "Knowing first and living by it: one's own sheet, the reporter who breaks the story, the column that makes a name."),
        R=('the ballad-seller', 'News that stirs: the ballad of a scandal sung in every street, the call that fills the square by evening.'),
        G=('the neighbour who knows every family', "Talk as the kin's net: who was born, who is ill, who needs a hand, passed from the well to the doorstep.")),
    "arts.song": dict(name='the concert hall', kind='Song and dance',
        W=('choir leader', 'The memorial concert: every choir on one stage, cheap seats and a song all know, as once at the dance ground.'),
        U=('conductor', 'An instrument to master: the orchestra rehearsing one passage until the sound is true in every seat.'),
        B=('promoter', "A night to sell out under one's own name, the fee and the next tour agreed in the back room."),
        R=('bandleader', 'Chairs pushed back when the band strikes up, the crowd on its feet, singing the chorus back.'),
        G=('fiddler of the old tunes', 'The old tunes night: the reels the grandparents danced, played by their grandchildren to the same families.')),
    "arts.stage": dict(name='the theatre', kind='Theatre and opera',
        W=("manager of the town's company", 'A public good: the classic season at fair prices, a seat for every schoolchild, plays that show a town its right and wrong.'),
        U=('director', 'A design to perfect: voice, orchestra, light and stage working as one, refined over months of rehearsal.'),
        B=('actor-manager or impresario', "A venture: the patrons' boxes, the singer whose name fills the house, a company run on one's own fortunes."),
        R=('player', 'Raw and close: the satire the cheap seats roar at, love and fury sung at full volume.'),
        G=('member of the community players', "The neighbours' stage: the same winter play each year, costumes sewn by the cast, the same families in the same seats.")),
    "arts.screen": dict(name='the cinema and home screen', kind='Screen and shadow play',
        W=("keeper of the town's picture house", 'The shared story: the film a whole town sees in one week and talks over at every table.'),
        U=('film editor', 'Each frame studied and cut forty ways until the scene says exactly what it should, as the shadow-play master trimmed each figure.'),
        B=('producer', "The star who picks their own roles, and the producer who bets a fortune on the first night's queues."),
        R=('maker of cheap late-night films', 'The late show where the crowd shouts at the screen, gasps and weeps together in the dark.'),
        G=('film-maker in the home tongue', "Films in the home tongue about one's own valley, shown in the village hall to the faces in them.")),
    "arts.tale": dict(name='the fireside and the phone', kind='Tales and lore',
        W=('teller of the teaching tales', 'Where every child hears the tales of right and wrong, the same ones their parents heard.'),
        U=('collector of tales', 'Where the collector writes each telling down, notes who told it, and traces where it came from.'),
        B=('teller with a following', 'Where a gifted teller earns a name and a living: the best stories asked for, and paid for, by name.'),
        R=('teller of ghost stories', 'Where the ghost story is told to make everyone jump, and the funniest liar wins the night.'),
        G=('keeper of the tellings', 'Where the legends of this hill and this river are told so they stay true, and the dead are named.')),
    "arts.page": dict(name='the bookshop', kind='Page and print',
        W=('editor of the common reader', "Books for everyone: the reader every child learns from, the town's chronicle kept for all, as the scribe's stall once kept it."),
        U=('editor', 'Words weighed and revised: the long margin notes, the poem rewritten until every line holds.'),
        B=('publisher', 'Rights bargained and a name made: the signing queue, the writer who owns their own work at last.'),
        R=('poet of the open night', 'The poetry night in the back room: verses written that afternoon, read aloud and passed hand to hand.'),
        G=('printer of local writing', "The shelf of local writing: the valley's legends in print, the family recipes, the songs of the place.")),
    "arts.craft": dict(name='the gallery', kind='Image and craft',
        W=('keeper of the public gallery', "The town's treasures shown free to all and cared for, so every child can see them, as the temple wall once showed them."),
        U=('restorer', "Where the restorer learns from the old masters' brushwork and the craft is judged line by line."),
        B=('dealer', 'The opening night: prices agreed, collectors courted, the artist who sets their own price at last.'),
        R=('painter of the pop-up show', 'The pop-up show in an empty shop: paint still wet, music loud, everyone a friend by midnight.'),
        G=('carver or weaver', 'The room of quilts, carvings and pots by local hands, each pattern older than the town.')),
    "arts.rite": dict(name='the festival ground', kind='Ceremony and festival',
        W=('festival steward', 'The festival with room for everyone: free entry, a place in the parade for each ward, the memorial at noon.'),
        U=('festival programmer', 'A programme planned for a year: the order of acts, the sound and the light worked out so each turn lands.'),
        B=('festival founder', 'A venture built from nothing: sponsors, tickets, and a name every act wants on its record.'),
        R=('dancer on the last night', 'The last night, when no one wants to go home and strangers dance in the mud till dawn.'),
        G=('dance leader', "The folk festival of the year's round: the same dances on the same weekend, three generations in one ring, as at the summer gathering.")),
    "faith.congregation": dict(name='the house of worship', kind='Congregations',
        W=('elder of the congregation', 'A home where the same is asked of all: the rota, the alms, a seat for the widow and the newcomer alike.'),
        U=('leader of the study circle', 'A school for the soul: the teaching read closely after the rite, and questions asked aloud and taken seriously.'),
        B=('member who chose this house', 'A faith one chose: switched to, joined or founded with friends, a place to rise and be heard.'),
        R=('worship singer', 'Where the sacred is felt: singing that will not stop, the stranger who weeps and comes back next week.'),
        G=('family on the same bench for generations', "Where one's people have always met: the same families, the dead named; at the fire, the same clans in the same circle.")),
    "faith.rites": dict(name='the funeral home', kind='Rites of passage',
        W=('keeper of the graves fund', "One rite for rich and poor: the same words, the same ground, the neighbours' coins paying for the pauper's grave."),
        U=('keeper of the burial register', 'A record of who lived: the names written down, the stones read, the family lines traced back.'),
        B=('family that buys its own plot', "A family's chosen place: a plot bought, a stone carved to its taste, the funeral planned in one's own words."),
        R=('singer at the graveside', 'Grief said out loud: the wake that turns to song, the farewell that makes mourners laugh and cry at once.'),
        G=('keeper of the family graves', "Where the family stays together: graves swept each spring, the dead told the news; once, the ancestors' places on the walk.")),
    "faith.calendar": dict(name='the holidays at home', kind='The sacred year',
        W=('steward of the feast', 'A day the same for everyone: rest for the servant as well as the master, the feast shared out evenly.'),
        U=('reckoner of the calendar', 'A year that must be reckoned right: the moon and the seasons checked, so the feast days stay true.'),
        B=('stallholder at the feast fair', 'A holy day as a chance: the fair that comes with the feast, a vow paid in public, a name made.'),
        R=('leader of the procession', 'The day the sacred breaks loose: drums, dancing, a procession that takes the whole street with it; once, the dance ground.'),
        G=('keeper of the feast days', "The year's round come again: the same dishes, the same songs, the family home for the feast as always.")),
    "faith.orders": dict(name='the retreat community', kind='Vowed houses and specialists',
        W=("keeper of the house's hours", 'A life given wholly to duty: the hours kept, the poor fed at the gate, one rule for every member.'),
        U=('scholar under vows', 'A life given to study and stillness: the library, the long practice, questions no one outside has time for; once, the lore lodge.'),
        B=('able child of a poor family taken in', "A ladder: a poor child taught to read who rises to run the house's lands or sit among the faith's leaders."),
        R=('novice who came on a burning call', 'A calling that would not wait: everything left in a week, vows taken young and with joy.'),
        G=("keeper of the house's fields and bees", 'A house that farms the same fields for centuries, keeping the old seed, the bees and the grove.')),
    "faith.works": dict(name='the food bank', kind='Works of faith',
        W=('steward of the alms', "No one turned away hungry: bread by rota, given alike, the giver's name not asked."),
        U=('organiser who finds the cause', 'Help that works: who is hungry and why, a list kept, the aid aimed where it does most good.'),
        B=('founder who runs it on gifts', "A work one built: a kitchen founded and run on one's own drive, its givers courted, its name made."),
        R=('volunteer who comes at night', 'Help now, without forms: the hot meal at midnight, the stranger fed before any question.'),
        G=("cook with the family's recipes", 'Neighbours feeding neighbours: the same families cooking for the bereaved and the poor, as their parents did; once, the shared kill.')),
    "faith.seeking": dict(name='the retreat house', kind='Questions and doubt',
        W=('warden of the retreat', 'A shared rule of quiet: the bell, meals in silence, everyone keeping the same hours.'),
        U=('meditation teacher', 'A place to look inward and understand: the long sitting, the old texts, doubt faced honestly.'),
        B=('seeker remaking their life', 'A turning point chosen: the week away that ends a marriage, starts a calling or changes a faith.'),
        R=('seeker on a vision fast', 'The vision sought in the body: fasting, the night vigil, the moment the heart breaks open; once, the lonely place of the vision walk.'),
        G=('guide of the hill walks', "Back to the land and the old ways: the walk in the hills, the spring, the quiet one's people have always known.")),
    "faith.shrines": dict(name='the old walking road', kind='Shrines and pilgrim roads',
        W=('shrine keeper who tends it for all', 'A place open to everyone: kept clean by turns, a lamp lit for any traveller.'),
        U=('pilgrim who reads the stones', 'A place to learn from: the inscriptions read, old stories compared, the road walked with questions.'),
        B=('pilgrim with a vow', 'A place to bargain: the vow made at the shrine, the offering hung, the favour asked and paid for.'),
        R=('walking pilgrim who sings the road', 'A place to reach on foot and feel: the long walk, blistered and singing, joy at the last hill.'),
        G=('family that keeps the spring', "A place one's people have always come: the spring the family has always walked to, the land itself held sacred.")),
    "care.hearth": dict(name='the kitchen table at home', kind='Home and kin',
        W=('the sister who draws up the rota', 'A sickroom run fairly: the siblings share the nights by rota, and no one is left to carry it alone.'),
        U=('the carer with the notebook', 'A sickroom that is studied: doses and bad nights written down, the remedy book open, the pattern found.'),
        B=('the son who hires help and keeps his own work', "A sickroom on one's own terms: paid help chosen and hired, the carer's own work and plans kept going."),
        R=('the grandchild who moves home', 'A sickroom with life in it: music, visitors, the favourite food, and someone who dropped everything to be there.'),
        G=('the daughter who nurses as her mother did', "The sickroom as it has always been: kin take turns, old remedies, the body's own pace.")),
    "care.birth": dict(name='the maternity unit', kind='Birth',
        W=('sworn midwife of the town', 'Every birth attended by a trained midwife, whoever the mother is, and every birth written in the register.'),
        U=('the midwife who washes her hands and counts', 'Births counted and compared: what kills mothers is found and changed, one practice at a time.'),
        B=('the mother who chooses where and with whom', "A birth on the mother's own terms: the attendant she chooses, the room she pays for, the plan she keeps."),
        R=('the neighbour who catches the early baby', 'The baby that comes too fast: whoever is there kneels down and catches it, laughing and crying.'),
        G=('the aunt who has caught every baby in the family', "Birth as the family's women have always done it: old songs, a warm room.")),
    "care.healers": dict(name='the pharmacy', kind='Healers and remedies',
        W=('the dispenser who keeps one price for all', 'A shop with one fair price and an honest weight, which gives on credit to the sick poor.'),
        U=('apothecary who tests what he sells', 'A shop where every remedy has been tried and recorded, and the doubtful ones come off the shelf.'),
        B=('apothecary with a remedy under her own name', "A shop of one's own: a name above the door, a remedy no one else can make, the price set by the seller."),
        R=('the herb-seller who opens at midnight', 'The shop that opens its shutter at midnight for a feverish child, and argues about the bill later.'),
        G=('herbalist who grows what she sells', "Remedies from the family's garden and the hedgerow, made the way the family always has.")),
    "care.physic": dict(name="the doctor's rooms", kind='Physic and surgery',
        W=('the doctor who sees patients in turn', 'Rooms where patients are seen in the order they came, the labourer before the lord if he came first.'),
        U=('physician who trains apprentices', 'Rooms where each case is examined, written up and compared, and the young learn by doing it right.'),
        B=('doctor with a name of her own', "Rooms of one's own: a plate on the door, loyal patients, terms set without asking a board's leave."),
        R=('the doctor who goes out at night', 'Rooms left empty because the doctor is out on a night call, bag in hand, through the snow.'),
        G=('the family doctor who knew the grandparents', 'Rooms where the doctor has known three generations of a family and treats the person, not only the illness.')),
    "care.houses": dict(name='the hospital', kind='Houses of care',
        W=('head of nursing', "A house open by need: a bed for anyone who knocks."),
        U=('chief physician who keeps the case books', 'A house that learns: every death reviewed, every ward compared, the better way taught to the next intake.'),
        B=('governor who built the private wing', 'A house built by ambition: the endowed wing with a name over the door, the private rooms that pay for the rest.'),
        R=('the nurse who keeps the long ward laughing', "A house with a pulse: the porter's jokes, music on the long ward, birthdays kept for the dying."),
        G=('the volunteer who sits with the lonely', 'A house that is still a home: families come and go, old customs at the bedside, the dying among their own.')),
    "care.rescue": dict(name='the ambulance and emergency room', kind='First aid and rescue',
        W=('triage nurse', 'Triage by need: the worst hurt seen first, whoever they are, and every case logged for the next shift.'),
        U=('emergency doctor who drills the team', 'A room run on drills and checklists, practised until the team moves as one under pressure.'),
        B=('the medic who takes the hard shifts at her own price', "A place to make one's name on nerve: the shifts that pay double, the cases others avoid, a reputation earned."),
        R=('paramedic', 'The rush through the doors: nerve, speed, a joke that steadies the scared.'),
        G=("the night nurse who knows the town's families", 'A room where staff know the families: the next of kin are called first and the neighbours sit with the frightened.')),
    "care.public": dict(name='the health board', kind='Public health',
        W=('health officer', 'One rule for every street: the same water, the same drains, the same inspection for all.'),
        U=("the board's counter of deaths", 'A board that counts: deaths by street, wells tested, the cause found before the order is given.'),
        B=('contractor who builds the waterworks', 'A board that deals: contracts for the waterworks, and a doctor who builds a name on a cleaner town.'),
        R=('volunteer who goes door to door in the epidemic', 'A board that needs runners: volunteers going door to door with water and news when the sickness comes.'),
        G=('the well-keeper whose family has kept the spring', 'A board that listens to the old keepers of wells and springs, who know which water was always clean.')),
    "learn.rearing": dict(name='the home and the nursery', kind='First teaching',
        W=('the parent who gives every child the same chores', 'Every child gets a turn and a task, and the slowest is waited for; at the early hearth, no child is left out of the tellings.'),
        U=('the parent who answers every why', 'The home as a place of questions: the clock taken apart, the stars named, the answer looked up together.'),
        B=("the parent who plans the child's start", 'The home as a head start: early letters, the right friends, a child taught to speak up for what they want.'),
        R=('the older sibling who lets the little ones try', 'The home as a first workshop: the knife, the fire and the ladder tried under a watchful eye, and learning by getting it wrong.'),
        G=('the older cousin who teaches by doing it beside them', 'The home as the first school of a people: the recipes, the tongue, the songs and the chores, the way they always were.')),
    "learn.schooling": dict(name='the school', kind='Schools',
        W=('the teacher who counts every child in', 'A school for all: the same lesson, fair marks, and the child from the far farm walked home when it snows.'),
        U=('the teacher who asks why', "A school for thinking: the lesson as a puzzle, the wrong answer worked through, the pupil's question taken seriously."),
        B=('the pupil set on the top marks', 'A school as a ladder: the right subjects, the top of the class, the reference that opens the next door.'),
        R=('the teacher who takes the class outside', 'A school that moves: the experiment that smokes, the play put on, the lesson taken outdoors because the day is fine.'),
        G=('the teacher born in the valley', "A school that belongs to its place: local songs, the home tongue, the same families' names on the desks for generations; earlier, the elders' teaching.")),
    "learn.apprentice": dict(name='the training centre', kind='Apprenticeship and training',
        W=('the master who keeps the indenture fair', 'Fair terms kept on both sides: the hours, the food, the lessons promised, and the papers signed at the end.'),
        U=('the master who explains why the joint holds', "The workshop as a school of method: why the glaze cracks, why this temper holds, written in the master's notebook."),
        B=('the journeyman saving for a bench of their own', "The workshop as a start: learn the trade's secrets, gather the customers, and one day open one's own door."),
        R=('the apprentice who tries before being told', 'The workshop as a playground of hands: spoil the first ten, finish the eleventh, learn the feel no book gives.'),
        G=('the family master training a niece', "The trade handed down: the same marks, the same tools, the family's way, and the young one who will carry it on.")),
    "learn.higher": dict(name='the university', kind='Academies and higher learning',
        W=('the admissions tutor who keeps places open to the poor', 'The academy as a public trust: places by merit and need, an oath to serve, learning owed back to the town.'),
        U=('the scholar at the long table', 'The academy as a house of questions: proof, doubt, the old book argued with, years given to one problem; earlier, the lore lodge.'),
        B=('the student who chose the course for the post it opens', "The academy as a door to rank: the right teacher's name, the friends made, the degree that sets one's price."),
        R=('the student who argues till dawn', 'The academy as a time of fire: the debates, the friendships, the night the whole year marched for something.'),
        G=("the student who carries on her teacher's line", "The academy as a lineage: teacher to student back through the years, the hall's old customs, the founder's tree in the yard.")),
    "learn.keeping": dict(name='the library and archive', kind='Libraries and archives',
        W=('the librarian who lends to anyone', 'The library as a common good: open doors, the same rules for all, the card that costs nothing.'),
        U=('the cataloguer', 'The library as order: every book where it can be found, and the index that turns a heap into knowledge.'),
        B=('the collector of rare books', 'The library as a treasury: the rare volume, the private room, knowledge held as a holding that gives its keeper standing.'),
        R=('the reader who borrows ten at once', "The library as an adventure: the shelf found by chance, the book read under the table, the poster for tonight's talk."),
        G=("the keeper of the town's records", "The library as memory: births, deeds and old songs kept for children not yet born; earlier, the teller's long memory.")),
    "learn.finding": dict(name='the lab', kind='Research and finding',
        W=('the reviewer who keeps the method honest', 'Research by sound rules: every result checked, credit shared fairly, findings published for anyone to use.'),
        U=('the researcher at the bench', 'The lab as a place to find out: the long question, the failed trial written down, the one result that changes the map.'),
        B=('the founder who sells the finding', 'The lab as a source of advantage: the patent, the prize, the private contract that pays for the next ten years.'),
        R=('the tinkerer who tries the wild idea', 'The lab as play: try it tonight, and if it sparks, show everyone; earlier, the star-watcher on the temple roof.'),
        G=('the long-watch recorder', 'Research as patience: forty years of the same field counted, the slow change only a lifetime can see.')),
    "prod.wild": dict(name='the fishing boat', kind='Hunt, gather and fish',
        W=('the skipper who shares the catch by the old lay', "A crew bound by fair shares: the lay divides the catch, as the band's hunters once divided the kill."),
        U=('the skipper who logs every catch', 'A way to learn the sea: log the catch, the wind and the water, and find the fish before the others.'),
        B=('the boat owner who hires the crew', "A stake of one's own: own the hull, hire the hands, and sell where the price is best."),
        R=('the deckhand who signs on for the long trip', 'The open sea before dawn: the big catch, the weather dared, and a crew one chose, as the hunt once was.'),
        G=('the crew of cousins', 'A living on the water kept for the next crew: the spawning grounds spared and the boat handed on, as the weir was.')),
    "prod.land": dict(name='the family farm', kind='Farm and herd',
        W=('the keeper of the shared harvest rota', "A share in the common work: the rota, the shared harvest, and no neighbour's field left standing."),
        U=('the farmer with a trial strip', 'A place to find out: the trial strip, the yield book, the new seed tested before it is trusted.'),
        B=('the farmer who buys the next field', 'Ground one owns and grows: lease it, buy it, add to it, and sell the crop where it pays.'),
        R=('the hand who breaks the horses', "A life outdoors on one's own hours: the high pasture, the horse broken in, the race to beat the rain."),
        G=('the young heir who takes on the family farm', 'Ground kept for those who come after: rested, read by the sky, and handed on whole.')),
    "prod.ground": dict(name='the open-cast mine', kind='Mine, quarry and wood',
        W=('the shift boss who checks the props', 'Everyone who goes down comes up: the props, the air and the rules kept, from the first flint pits on.'),
        U=('the surveyor who maps the seam', 'A puzzle in rock: map the seam, test the air, and find the safer, deeper way.'),
        B=('the claim-holder', 'A claim worth staking: find the vein, raise the money, hire the crew and sell the ore.'),
        R=('the prospector', 'The rush to new ground: the first strike, the rough camp, the luck that might be waiting.'),
        G=('the miner who teaches the new starters the seam', 'A living that lasts: the seam worked with care, the new starters taught, and the village it built kept alive.')),
    "prod.craft": dict(name="the maker's workshop", kind='Craft',
        W=("the master who judges the apprentice's piece", 'A place that keeps a standard: honest goods, a fair price, and every apprentice taught the whole trade.'),
        U=('the maker who refines the method', 'A place to perfect a method: the better glaze, the truer joint, the jig that saves an hour.'),
        B=('the master who buys the shop', "A business of one's own: one's own name over the door and one's own hands hired, grown from the household bench."),
        R=('the maker who makes only what moves her', "Freedom to make: one's own hours, the music loud, the thing made because it moves them."),
        G=("the apprentice who will carry on the master's bench", 'Work that outlasts the maker: the old pattern kept alive, the next hands taught, the trade passed on.')),
    "prod.works": dict(name='the factory floor', kind='Works and factories',
        W=('the shop steward', 'A promise kept: fair pay, safe machines, the contract read aloud, and no one let go without warning.'),
        U=('the production engineer', 'A system to improve: time the line, find the waste, redesign the tool so the work goes better, as in the first mills.'),
        B=('the owner who started with one machine', 'What one built: the risk taken, the orders won, the firm that grew from one machine.'),
        R=('the line hand who starts the walk-out', 'A cage or a crew: the joke on the line, the pay-day night, the walk-out when it goes too far.'),
        G=('the third-generation hand who trains the new starters', "The town's living kept for its children: the new starters trained, the works team, the street that grew around the mill.")),
    "prod.founding": dict(name="the start-up's rented unit", kind='Founding and enterprise',
        W=('the founder of a cooperative', "A fair way to work: a co-op or a mutual, shares split by rules the members set, like a new crew's agreed share."),
        U=('the founder who tests the idea first', 'An idea proven: plans, trials and figures before the first coin is risked.'),
        B=('the founder with a loan', "A chance to steer one's own life: the loan signed, the gap found, the hands hired."),
        R=('the founder who quits to make the thing', 'A leap: quit the job, make the thing one cannot stop thinking about, and see.'),
        G=('the parents who found a firm for their children', "A trade built to last: the family recipe, the village's craft, a living for those who stay, as kin once founded a new camp.")),
    "comm.gift": dict(name='the wedding gift table', kind='Sharing and return gifts',
        W=('the host who thanks every gift alike', "Each guest gives what they can and is thanked the same; the poor cousin's gift is as welcome as the rich one's."),
        U=('the aunt who keeps the gift book', 'A list of who gave what, so each gift can be returned at the right size and time.'),
        B=('the guest whose gift is talked about', 'A generous gift that makes a name and leaves the right people owing.'),
        R=("the friend who gives a month's wages", "Giving beyond one's means because the day deserves it."),
        G=('the cousin who remembers what each family gave last time', 'Gifts that answer gifts of a generation ago and bind two families again; once the feast at the gathering.')),
    "comm.market": dict(name='the open-air market', kind='Markets and fairs',
        W=('the market warden', 'Scales checked in the open, pitches given by turn, disputes settled before the stalls close.'),
        U=('the buyer who walks every row first', "Knowing each stall's prices and the day's best buy before a coin is spent."),
        B=('the stallholder who built a pitch from nothing', "A stall of one's own, the regulars it wins, and a second stall next year."),
        R=('the trader who sings the price', 'Haggle and dare: the noise, the bargaining, the thrill of the find.'),
        G=('the stallholder whose regulars are her neighbours', "The town's living room, where everyone shops, gossips and is known; once the trading ground at the clans' gathering.")),
    "comm.shop": dict(name='the supermarket', kind='Shops and stalls',
        W=('the shopkeeper with one price for all', 'Prices on the shelf, the change counted back, and no one sold short.'),
        U=('the shopkeeper who stocks by the season', "Shelves filled by last year's sales and next week's weather, so little spoils and little runs out."),
        B=('the newcomer owner who opens seven days', 'A shop on borrowed money, long hours, and a family that answers to no master.'),
        R=('the shopkeeper who sells from the doorstep', 'The shop as a stage: the window dressed for the season, the doorstep talk, the deal called out to passers-by.'),
        G=('the grocer with the tab book', "Credit on a name, the same families for decades, and news of every birth; once the chandler's stall.")),
    "comm.far": dict(name='the import house', kind='Far trade',
        W=('the agent who honours every contract', 'Trade under shared rules: fair contracts, honest measures and safe passage for every trader.'),
        U=("the clerk who knows every route's season", "Knowing the routes, the seasons and far prices better than anyone, from the caravan's day to the freight timetable."),
        B=('the importer who started with one crate', "Venture far on one's own account and come back owing no one."),
        R=('the buyer who travels to find what no one else sells', 'The road itself: new towns, new faces, the risk of the crossing.'),
        G=("the cousin who runs the family's branch abroad", 'Kin in far ports who trust each other, so goods move on a word between relatives; once gift partners across the mountains.')),
    "comm.credit": dict(name='the bank branch', kind='Credit and money',
        W=('the clerk who explains the terms twice', 'Savings kept safe, honest terms, and no family ruined over one missed week.'),
        U=('the loan officer who reckons the risk', "Credit priced by careful reckoning of risk and return; once the temple scribe's loan tablets."),
        B=('the borrower who builds with the loan', 'Credit as a tool: borrow to build, never to be bound.'),
        R=('the customer who takes the chance while it is there', 'The loan that lets someone take the chance now, before it is gone.'),
        G=('the young clerk who knows every family on the street', "A bank that lends on a family's name and years, like the seed loan between neighbours it grew from.")),
    "comm.office": dict(name='the office floor', kind='Counting-house and working centre',
        W=('the payroll clerk', 'Clear records and fair rules, so wages are paid on the day and no one is cheated.'),
        U=('the manager who redesigns the work', "Systems that make the work run better: the ledger, the schedule, the plan; once the counting-house's double columns."),
        B=('the junior who wants the corner desk and says so', 'A desk one climbs from, or a business run from a rented room.'),
        R=('the one who keeps the floor laughing at the deadline', 'The busy floor with its rushes and friendships, work done together against the clock.'),
        G=('the colleague of thirty years', "Colleagues who become family and mark each other's births, weddings and losses.")),
    "comm.hire": dict(name='the job centre', kind='Hiring and the labour market',
        W=('the clerk who lists every job the same way', 'Fair hiring: the same rules, a written wage, no one turned away for who they are.'),
        U=('the adviser who matches skills to posts', "The right person for the right job by what they can do; once the labour exchange's card index."),
        B=('the jobseeker who names her own rate', "Selling one's own work on one's own terms, to the best bidder."),
        R=('the day worker who takes what comes', 'Take the work that comes today and move on when one likes; once the day-labour corner at dawn.'),
        G=('the uncle who vouches for his nephew', "Work found through kin and neighbours; once the trade's house of call where everyone knows you.")),
    "prot.watch": dict(name='the police station', kind='The watch',
        W=('constable', 'One law walked the same way through every street, the rich quarter and the poor lane alike.'),
        U=('detective who reads the pattern', 'A place to learn: patterns in the thefts, evidence weighed, and the wrong suspect freed.'),
        B=('officer who wins the promotion', 'A career one steers: cases solved, rank won, a name that opens doors and a pension earned.'),
        R=('constable who runs in first', 'The officer who runs toward the shouting when everyone else runs away.'),
        G=('beat officer who knows every family', 'The constable who knows every family on the beat; in the band, the peace-keepers who know every quarrel.')),
    "prot.host": dict(name='the armed forces', kind='The host',
        W=('soldier of the line', 'Service and discipline: a duty to defend the whole people, under orders and the laws of war.'),
        U=('staff officer', 'Supply, maps and the long study of how wars are won, or better, avoided.'),
        B=('specialist who picks the posting', "Service on one's own terms: a trade learned, a commission earned, a pension and a name to carry home."),
        R=('volunteer of the forward company', 'Comradeship under fire and the courage to go first; in the war band, the hunter singing at dawn.'),
        G=('home guard reservist', 'Defend the home ground, its fields and families, never a war of conquest far away.')),
    "prot.hire": dict(name='the security firm', kind='Force for hire',
        W=('guard who keeps one rule for every client', "One rate and one rule for every client: the corner shop's door guarded as closely as the bank's."),
        U=('security adviser', 'Professionals who study the threat and sell what they know: the risk report, the safe route.'),
        B=('sellsword or firm owner', 'Skill sold openly at its worth, to whoever pays, owing no lord.'),
        R=('caravan guard on the far road', 'Adventurers who take the far road for the pay, the danger and the story.'),
        G=('guard in a family firm', "A company of kin and neighbours who look after each other's families between contracts; in the band, allies paid in gifts.")),
    "prot.watchers": dict(name='the control room', kind='Watchers',
        W=('keeper of the watch log', 'A record kept honest: every report written down, every arrest accounted for, open to the court.'),
        U=('analyst', 'See it first: signs read, patterns found, the warning sent in time; once, the lookout rock.'),
        B=('private investigator', "What one knows is worth something: a case taken for a fee, a client's secret kept."),
        R=('scout who rides out', 'The scout who goes out alone past the last fire to see with their own eyes.'),
        G=('young neighbour who notices', 'The young one on the doorstep who knows every face on the street, and who might need help.')),
    "prot.walls": dict(name='locks, lights and cameras', kind='Walls and arms',
        W=('keeper of the common walls', 'Walls, lamps and locks for every street, paid from the common purse, not only for those who can buy them.'),
        U=('military engineer', 'Defences designed and tested: the angle of a wall, the lamp at the dark corner, the better lock.'),
        B=('armourer or locksmith with a shop', 'A trade in safety: arms, locks and alarms made well and sold at their worth.'),
        R=('smith who tries the new blade', 'The forge where a new blade or bell is tried at once, loudly, and fixed by morning.'),
        G=('neighbour who mends the palisade', 'The wall everyone mended after the last raid; each family knows its stretch and keeps it.')),
    "prot.rescue": dict(name='the fire and rescue station', kind='Fire and rescue',
        W=('firefighter on the rota', 'Help for every house that burns, rich or poor, the bell answered the same each time.'),
        U=('fire inspector', 'Fires prevented rather than fought: rules for chimneys, hydrants, drills and ways out.'),
        B=("insurers' salvage crew", 'A crew paid by the insurer to save goods, and paid better the more it saves.'),
        R=('volunteer firefighter', 'The bell rings and the volunteers run, glad of the danger and of each other.'),
        G=('neighbour in the bucket line', 'The whole street in the bucket line, and the burned-out family taken in by neighbours that night.')),
    "prot.holding": dict(name='prison and probation', kind='Holding and return',
        W=('prison officer', 'Every prisoner held by the same rules, fed, counted, and released on the day the law says.'),
        U=('probation officer or prison teacher', 'A sentence used to change what led to it: a trade learned, a reading class, a plan for release.'),
        B=('owner who hires people with records', 'A second chance as a shrewd bet: the owner who hires people with records and judges them by their work.'),
        R=('friend who keeps visiting', 'The friend who visits every month, and meets the release day with a loud welcome.'),
        G=('family who take them home', "Taken back by one's own people as they are; in the band, the exile allowed home after a season.")),
}

RUNG = {
    'rule': ['one of the people', 'one who speaks up', 'one whose word counts', 'one who holds a seat', 'one who leads the rule'],
    'gather': ['newcomer', 'regular', 'known face', 'pillar', 'host'],
    'arts': ['listener', 'player', 'known voice', 'master', 'voice of their people'],
    'faith': ['newcomer at the rites', 'one of the faithful', 'known voice', 'elder', 'keeper of the faith'],
    'care': ['patient', 'helping hand', 'trusted carer', 'healer people send for', 'head of a house of care'],
    'learn': ["a learner at someone's side", 'one who can do it alone', 'one whose knowing is trusted', 'one who teaches', 'a master others come to'],
    'prod': ['a helper', 'a hand', 'a skilled hand', 'a master of the work', 'the one who runs the work'],
    'comm': ['one who buys and owes', 'a hand behind the counter', 'a trader on their own account', 'a name trusted with credit', "a house that sets the market's terms"],
    'prot': ['one the guard keeps', 'one who takes a turn on watch', 'a seasoned hand', 'one who leads a watch', 'one who commands the guard'],
}

PLACE_SHORT = {
    ('gather.games', 'sail'): 'the river race and bowls',
    ('arts.stage', 'villages'): 'the shrine mask dance',
    ('arts.stage', 'realms'): 'the pageant wagon',
    ('arts.screen', 'realms'): 'the fair puppet booth',
    ('arts.screen', 'modern'): 'the cinema and home screen',
    ('arts.tale', 'machine'): 'the rest-day kitchen fire',
    ('arts.tale', 'magic'): "the night market tellers' corner",
}
